/**
 * Glossary: every term a new player meets, every employee card, every milestone and every Ketchup
 * concept, in plain English. Written for someone who has never played. Facts follow docs/rules/*
 * (base.md, employees.md, milestones.md, map.md, ketchup.md); `rule` is the rules-book section id
 * (ui/rules/book.ts) that explains it in full. Ids are stable snake_case; tests check that every
 * `related` id and `rule` anchor resolves and that every card, milestone and food has an entry.
 */
import type { EmployeeId, FoodId, MilestoneId, ModuleId } from '@fcm/engine';

export type GlossaryGroup = 'basics' | 'phases' | 'company' | 'board' | 'dinner' | 'marketing' | 'money' | 'food' | 'employee' | 'milestone' | 'ketchup';

export const GROUP_LABELS: Record<GlossaryGroup, string> = {
  basics: 'Basics',
  phases: 'Phases',
  company: 'Your company',
  board: 'The board',
  dinner: 'Selling food',
  marketing: 'Marketing',
  money: 'Money and the bank',
  food: 'Food and drinks',
  employee: 'Employee cards',
  milestone: 'Milestones',
  ketchup: 'Ketchup expansion',
};

export interface GlossaryEntry {
  id: string;
  term: string;
  group: GlossaryGroup;
  /** One or two plain sentences. */
  short: string;
  /** A concrete example with numbers where it helps. */
  example: string;
  /** Other glossary ids worth reading next. */
  related: string[];
  /** Rules-book section id (`#/rules/<id>`). */
  rule?: string;
  /** Other words people search for. */
  aliases?: string[];
  /** Module that adds it (omitted = base game). */
  module?: ModuleId;
  /** The employee card this entry describes. */
  employee?: EmployeeId;
  /** The milestone this entry describes. */
  milestone?: MilestoneId;
  /** The food or drink this entry describes. */
  food?: FoodId;
}

const R = {
  turn: 'base-turn-structure',
  setup: 'base-setup',
  firstRestaurants: 'base-placing-the-first-restaurants',
  reserve: 'base-setting-goals-reserve-cards',
  playerCount: 'base-player-count-table',
  restructuring: 'base-phase-1-restructuring',
  order: 'base-phase-2-order-of-business',
  working: 'base-phase-3-working-9-5',
  mandatory: 'base-mandatory-vs-optional',
  steps: 'base-sub-step-order-strict',
  recruit: 'base-recruit',
  train: 'base-train',
  driveIns: 'base-open-drive-ins',
  campaigns: 'base-launch-campaigns',
  food: 'base-prep-food-drinks',
  houses: 'base-place-houses-gardens-new-business-developer',
  restaurants: 'base-place-or-move-restaurants',
  dinner: 'base-phase-4-dinnertime',
  payday: 'base-phase-5-payday',
  marketing: 'base-phase-6-marketing',
  cleanup: 'base-phase-7-cleanup',
  milestones: 'milestones-general-rules',
  milestoneTable: 'milestones-milestone-table-18',
  bank: 'base-breaking-the-bank-game-end',
  intro: 'base-intro-game-variant',
  geometry: 'base-geometry-definitions',
  roads: 'map-road-connectivity-rules',
  mapStructure: 'map-structure',
  newHouses: 'map-placeable-house-tiles-8-new-business-developer',
  gardens: 'map-gardens-8-tiles',
  marketingTiles: 'map-marketing-tiles-base',
  employees: 'employees-base-game-222-cards-6-ceos',
  legend: 'employees-card-legend',
  career: 'employees-career-tree-base',
  kEmployees: 'employees-ketchup-expansion-employees',
  components: 'base-components-base-game',
  kModules: 'ketchup-module-list',
  kGeneral: 'ketchup-general-expansion-rules',
  kDistricts: 'ketchup-new-districts-map-tiles',
  kLobbyists: 'ketchup-lobbyists',
  kMilestones: 'ketchup-new-milestones',
  kCoffee: 'ketchup-coffee',
  kKimchi: 'ketchup-kimchi',
  kSushi: 'ketchup-sushi',
  kNoodles: 'ketchup-noodles',
  kPriority: 'ketchup-combined-priority-kimchi-sushi-noodles',
  kKetchup: 'ketchup-ketchup-someone-sells-your-demand',
  kFry: 'ketchup-fry-chefs',
  kMass: 'ketchup-mass-marketeers',
  kNight: 'ketchup-night-shift-managers',
  kRural: 'ketchup-rural-marketeers',
  kGourmet: 'ketchup-gourmet-food-critics',
  kReserve: 'ketchup-reserve-prices',
  kStars: 'ketchup-movie-stars',
  kHard: 'ketchup-hard-choices',
  kSix: 'ketchup-six-players',
} as const;

// ---------------------------------------------------------------------------
// Basics and phases
// ---------------------------------------------------------------------------

const BASICS: GlossaryEntry[] = [
  {
    id: 'round',
    term: 'Round',
    group: 'basics',
    short: 'One pass through all seven phases, from Restructuring to Clean up. The game is a series of rounds until the bank breaks twice.',
    example: 'Round 1: you only have your CEO, so you hire one person. By round 5 you might have ten employees.',
    related: ['phase', 'game_end', 'restructuring'],
    rule: R.turn,
    aliases: ['turn'],
  },
  {
    id: 'phase',
    term: 'Phase',
    group: 'basics',
    short: 'A part of the round. There are seven, always in this order: Restructuring, Order of Business, Working 9–5, Dinnertime, Payday, Marketing and Clean up.',
    example: 'You build your company in Restructuring, sell food in Dinnertime and pay wages in Payday.',
    related: ['round', 'restructuring', 'order_of_business', 'working', 'dinnertime', 'payday', 'marketing_phase', 'cleanup'],
    rule: R.turn,
  },
  {
    id: 'turn_order',
    term: 'Turn order',
    group: 'basics',
    short: 'The order players act in during Working 9–5 and the order that breaks the last ties at Dinnertime. It is chosen again every round.',
    example: 'You picked position 1, so you hire, train and market before anyone else this round, and you win price ties that waitresses do not settle.',
    related: ['order_of_business', 'open_slots', 'tie_break'],
    rule: R.order,
  },
  {
    id: 'cash',
    term: 'Cash',
    group: 'money',
    short: 'Your money. Everyone starts with $0, and cash is public. The richest player wins when the game ends.',
    example: 'You sell 2 burgers at $10 to a garden house: 2 × $20 = $40 goes from the bank to your cash.',
    related: ['bank', 'game_end', 'payday'],
    rule: R.setup,
    aliases: ['money'],
  },
  {
    id: 'game_end',
    term: 'End of the game',
    group: 'money',
    short: 'The game ends after the Dinnertime in which the bank breaks for the second time. Most cash wins; a tie goes to the tied player earlier in turn order.',
    example: 'The bank hits $0 for the second time at house 12. Everyone is still paid for the rest of Dinnertime, then the game is over: no Payday.',
    related: ['bank_break', 'bank', 'cash'],
    rule: R.bank,
    aliases: ['winning', 'winner', 'game over'],
  },
  {
    id: 'setup',
    term: 'Setup',
    group: 'phases',
    short: 'Before round 1: build the map, place your first restaurant and secretly pick a reserve card.',
    example: 'With 3 players, the last player in turn order places first. Anyone who passed must place in a second go-round.',
    related: ['first_restaurant', 'reserve_card', 'map_tile'],
    rule: R.setup,
  },
  {
    id: 'first_restaurant',
    term: 'First restaurant',
    group: 'board',
    short: 'In setup, players place one restaurant each in reverse turn order, or pass and place in a second round. Its entrance must be next to a road and not on a tile that already has a restaurant entrance.',
    example: 'Bo put a restaurant on tile B2, so you cannot put your entrance on B2; you choose A1, next door.',
    related: ['restaurant', 'entrance', 'setup'],
    rule: R.firstRestaurants,
  },
  {
    id: 'restructuring',
    term: 'Restructuring',
    group: 'phases',
    short: 'Phase 1. Everyone secretly decides which cards work this round and where they sit under the CEO; then all reveal at once.',
    example: 'You put a Waitress, a Trainer and a Management Trainee in your three CEO slots, and a Kitchen Trainee under the Management Trainee.',
    related: ['structure', 'ceo_slots', 'beach', 'overfill'],
    rule: R.restructuring,
    aliases: ['phase 1'],
  },
  {
    id: 'order_of_business',
    term: 'Order of Business',
    group: 'phases',
    short: 'Phase 2. The player with the most open slots picks any free turn-order position first, then the next, and so on.',
    example: 'You left 2 slots empty and Bo left 0, so you choose first and take position 1.',
    related: ['open_slots', 'turn_order'],
    rule: R.order,
    aliases: ['phase 2', 'order'],
  },
  {
    id: 'working',
    term: 'Working 9–5',
    group: 'phases',
    short: 'Phase 3. In turn order, each player uses every card at work. Steps go in a fixed order: hire, train, drive-ins, campaigns, food and drinks, houses, restaurants.',
    example: 'On your turn your CEO hires a Kitchen Trainee, your Trainer trains a beach card, your Marketing Trainee places a billboard and your cook makes 3 burgers.',
    related: ['work_steps', 'at_work', 'mandatory'],
    rule: R.working,
    aliases: ['phase 3', 'work', 'working 9-5'],
  },
  {
    id: 'work_steps',
    term: 'Work steps',
    group: 'phases',
    short: 'Working 9–5 is done in strict steps: hire, train, open drive-ins, launch campaigns, prep food and drinks, place houses and gardens, place or move restaurants. You cannot go back to an earlier step.',
    example: 'You must train before you market, so a card you hire and train this turn cannot also place a campaign this turn.',
    related: ['working', 'hiring', 'training'],
    rule: R.steps,
    aliases: ['sub-steps', 'stages'],
  },
  {
    id: 'dinnertime',
    term: 'Dinnertime',
    group: 'phases',
    short: 'Phase 4. Houses with demand buy, one at a time in house-number order, from the chain with the lowest unit price plus distance. Nobody makes decisions: it is pure arithmetic.',
    example: 'House 18 wants a burger. You charge $10 and are 1 border away (11); Bo charges $10 and is 2 away (12). You sell.',
    related: ['demand', 'unit_price', 'distance', 'winning_a_sale', 'tie_break'],
    rule: R.dinner,
    aliases: ['phase 4', 'dinner'],
  },
  {
    id: 'payday',
    term: 'Payday',
    group: 'phases',
    short: 'Phase 5. First everyone may fire cards; then you pay $5 for every salaried card you own. If you cannot pay, you must fire until you can.',
    example: 'You own a Burger Cook and a Junior VP (both salaried): you pay $10. With $6 cash you must fire one of them.',
    related: ['salary', 'firing', 'cash'],
    rule: R.payday,
    aliases: ['phase 5', 'salaries'],
  },
  {
    id: 'marketing_phase',
    term: 'Marketing Campaigns (phase)',
    group: 'phases',
    short: 'Phase 6. Every campaign on the board runs, lowest number first, putting demand on the houses it reaches. Then each loses one duration token.',
    example: 'Billboard #11 next to house 5 runs: house 5 gets a burger token, and the billboard drops from 2 tokens to 1.',
    related: ['campaign', 'demand', 'demand_cap', 'duration'],
    rule: R.marketing,
    aliases: ['phase 6', 'marketing'],
  },
  {
    id: 'cleanup',
    term: 'Clean up',
    group: 'phases',
    short: 'Phase 7. Unsold food and drinks are thrown away, every card returns to your hand, coming-soon restaurants open, and milestones claimed this round close for everyone else.',
    example: 'You have 2 burgers left: they go back to the supply unless you have a freezer.',
    related: ['freezer', 'coming_soon', 'milestone', 'hand'],
    rule: R.cleanup,
    aliases: ['phase 7', 'cleanup'],
  },
  {
    id: 'mandatory',
    term: 'Mandatory (auto) effects',
    group: 'company',
    short: 'Most actions are optional, but some cards act whether you like it or not: price changes, waitress tips, the CFO bonus, salary discounts and drive-ins. Cards marked "auto" do this.',
    example: 'A Luxuries Manager at work always raises your price by $10, even in a round where you would rather be cheap.',
    related: ['pricing_manager', 'luxuries_manager', 'waitress', 'cfo', 'drive_in'],
    rule: R.mandatory,
    aliases: ['auto', 'optional'],
  },
  {
    id: 'intro_game',
    term: 'Intro game',
    group: 'basics',
    short: 'A gentler first game: no reserve cards, no salaries, no milestones, $75 per player in the bank, and the game ends the first time the bank breaks.',
    example: 'Three players in an intro game start the bank at $225 and never have a Payday.',
    related: ['bank', 'milestone', 'salary'],
    rule: R.intro,
  },
];

// ---------------------------------------------------------------------------
// Your company
// ---------------------------------------------------------------------------

const COMPANY: GlossaryEntry[] = [
  {
    id: 'ceo',
    term: 'CEO',
    group: 'company',
    short: 'You. The CEO is always at work, hires one person every turn and has 3 slots for other cards. It can never be fired or trained.',
    example: 'Round 1: your CEO is your only card, so your one action is the CEO’s hire, say a Waitress.',
    related: ['ceo_slots', 'structure', 'hiring', 'bank_break'],
    rule: R.restructuring,
    employee: 'ceo',
    aliases: ['chief executive'],
  },
  {
    id: 'ceo_slots',
    term: 'Slots',
    group: 'company',
    short: 'Places under a card where other cards can work; every card at work sits in one. Your CEO has 3 slots, and managers bring their own.',
    example: 'CEO slots: Waitress, Trainer, Junior VP. The Junior VP adds 3 more slots for non-managers.',
    related: ['ceo', 'manager', 'open_slots', 'overfill'],
    rule: R.restructuring,
    aliases: ['ceo slots', 'work slots'],
  },
  {
    id: 'structure',
    term: 'Company structure',
    group: 'company',
    short: 'The pyramid of cards at work this round: the CEO on top, cards in its slots, and cards in the slots of any managers. At most three levels.',
    example: 'CEO → Management Trainee → Kitchen Trainee and Errand Boy. That is the deepest it gets.',
    related: ['ceo', 'manager', 'ceo_slots', 'restructuring'],
    rule: R.restructuring,
    aliases: ['org chart', 'pyramid', 'company'],
  },
  {
    id: 'manager',
    term: 'Manager',
    group: 'company',
    short: 'A black card with slots of its own. Managers can only sit in a CEO slot, and their slots hold non-managers only.',
    example: 'A Management Trainee (2 slots) in a CEO slot lets you run 4 cards instead of 3. You cannot put a Junior VP under it.',
    related: ['management_trainee', 'junior_vp', 'ceo_slots', 'structure'],
    rule: R.restructuring,
    aliases: ['black card'],
  },
  {
    id: 'open_slots',
    term: 'Open slots',
    group: 'company',
    short: 'Empty slots on your CEO and on your managers at work. In Order of Business, more open slots means you choose your turn-order position earlier.',
    example: 'CEO with 3 slots, 2 used, plus a Management Trainee with 1 of 2 used: 2 open slots.',
    related: ['order_of_business', 'turn_order', 'ceo_slots', 'first_airplane'],
    rule: R.order,
  },
  {
    id: 'overfill',
    term: 'Overfill',
    group: 'company',
    short: 'Putting down more cards than your slots can hold. The penalty: every card except the CEO goes to the beach, and you play the round with the CEO alone.',
    example: 'Bo reveals 5 cards for 3 CEO slots and no manager. Bo’s whole team goes to the beach; only the CEO works.',
    related: ['ceo_slots', 'beach', 'restructuring'],
    rule: R.restructuring,
    aliases: ['too many cards', 'penalty'],
  },
  {
    id: 'hand',
    term: 'Hand',
    group: 'company',
    short: 'The cards you own that are not busy. In Restructuring you choose from your hand who works; at Clean up everyone comes back to it.',
    example: 'You own 6 cards in hand but only have room for 4 at work; the other 2 go to the beach.',
    related: ['at_work', 'beach', 'restructuring'],
    rule: R.cleanup,
  },
  {
    id: 'at_work',
    term: 'At work',
    group: 'company',
    short: 'A card in your company structure this round; only cards at work do their jobs. Being at work is also called "played".',
    example: 'Your Kitchen Trainee is at work, so it can make a burger on your turn; the Trainer on the beach does nothing.',
    related: ['structure', 'beach', 'used_card'],
    rule: R.restructuring,
    aliases: ['played', 'working'],
  },
  {
    id: 'beach',
    term: 'Beach',
    group: 'company',
    short: 'Where new hires and cards not working this round wait. Beach cards do nothing, but they can be trained and still cost salary.',
    example: 'You hire a Kitchen Trainee: it goes to the beach. Your Trainer can train it into a Burger Cook straight away, and it works next round.',
    related: ['hiring', 'training', 'salary', 'at_work'],
    rule: R.restructuring,
    aliases: ['on the beach'],
  },
  {
    id: 'hiring',
    term: 'Hiring',
    group: 'company',
    short: 'Taking a new entry-level card from the supply; it goes to the beach. Your CEO gives 1 hire a turn, and recruiters give more.',
    example: 'CEO plus a Recruiting Girl: 2 hires. You take a Waitress and an Errand Boy.',
    related: ['entry_level', 'beach', 'recruiting_girl', 'supply', 'first_hire_3'],
    rule: R.recruit,
    aliases: ['recruit', 'recruiting'],
  },
  {
    id: 'entry_level',
    term: 'Entry level',
    group: 'company',
    short: 'Cards with the sparkle icon. Only these can be hired directly; everything else is reached by training.',
    example: 'You can hire a Kitchen Trainee, but a Burger Cook only by training a Kitchen Trainee.',
    related: ['hiring', 'trainee', 'career_path'],
    rule: R.recruit,
    aliases: ['sparkle', 'entry'],
  },
  {
    id: 'trainee',
    term: 'Trainee',
    group: 'company',
    short: 'A cheap, salary-free starter card at the bottom of a career path: Management, Marketing and Kitchen Trainees. Train them to unlock stronger cards.',
    example: 'A Marketing Trainee places small billboards; trained up it becomes a Campaign Manager who can place mailboxes.',
    related: ['entry_level', 'training', 'career_path', 'management_trainee', 'marketing_trainee', 'kitchen_trainee'],
    rule: R.career,
  },
  {
    id: 'training',
    term: 'Training',
    group: 'company',
    short: 'Swapping a beach card for the next card on its career path. Each training action moves one step; the old card goes back to the supply.',
    example: 'Your Trainer turns a beach Errand Boy into a Cart Operator. The piles change: Errand Boy +1, Cart Operator −1.',
    related: ['career_path', 'beach', 'trainer', 'coach', 'guru', 'first_train'],
    rule: R.train,
    aliases: ['train'],
  },
  {
    id: 'career_path',
    term: 'Career path',
    group: 'company',
    short: 'The lines on a card that show what it can be trained into. Some cards (Waitress, Pricing Manager, Recruiting Girl, Trainer) have none.',
    example: 'Errand Boy → Cart Operator → Truck Driver → Zeppelin Pilot: three training steps from bottom to top.',
    related: ['training', 'trainee', 'entry_level'],
    rule: R.career,
    aliases: ['career tree', 'trains into'],
  },
  {
    id: 'salary',
    term: 'Salary',
    group: 'money',
    short: 'Cards with the money icon cost $5 each at Payday, whether they worked, sat on the beach or are busy with a campaign.',
    example: 'You own a Burger Cook, a Campaign Manager and a Waitress. Two have salaries: $10 at Payday.',
    related: ['payday', 'firing', 'busy_marketeer', 'first_train'],
    rule: R.payday,
    aliases: ['wages', '$'],
  },
  {
    id: 'firing',
    term: 'Firing',
    group: 'money',
    short: 'Sending a card back to the supply at Payday so you stop paying it. You may fire anyone except the CEO and busy marketeers; you must fire if you cannot pay.',
    example: 'You owe $15 and have $10, so you fire the Truck Driver: now you owe $10 and can pay.',
    related: ['payday', 'salary'],
    rule: R.payday,
    aliases: ['fire'],
  },
  {
    id: 'one_x',
    term: '1x card',
    group: 'company',
    short: 'A unique card: each player may own at most one of it, beach included. Only 1 copy is in play with 2–3 players, 2 with 4, and 3 with 5 or more.',
    example: 'Bo owns the only CFO in a 3-player game. Nobody else can train one while Bo has it.',
    related: ['supply', 'training'],
    rule: R.legend,
    aliases: ['unique', '1x'],
  },
  {
    id: 'supply',
    term: 'Supply (employee piles)',
    group: 'company',
    short: 'The piles of employee cards nobody owns. They are limited: when a pile is empty, nobody can hire or train into that card.',
    example: 'The Staff tab shows "Burger Cook ×0": you cannot train a Kitchen Trainee into a Burger Cook until someone fires one.',
    related: ['hiring', 'training', 'one_x'],
    rule: R.recruit,
    aliases: ['piles', 'staff', 'market'],
  },
  {
    id: 'busy_marketeer',
    term: 'Busy marketeer',
    group: 'company',
    short: 'A marketeer whose campaign is still running. It sits beside your company, takes no slot, cannot work, be trained or be fired voluntarily, and still costs salary.',
    example: 'Your Campaign Manager placed a 3-round mailbox. For the next 3 Marketing phases it is busy; you still pay its $5.',
    related: ['campaign', 'duration', 'salary', 'eternal_campaign'],
    rule: R.campaigns,
    aliases: ['busy'],
  },
];

// ---------------------------------------------------------------------------
// The board
// ---------------------------------------------------------------------------

const BOARD: GlossaryEntry[] = [
  {
    id: 'map_tile',
    term: 'Map tile',
    group: 'board',
    short: 'A 5×5 square of the town. The map is a grid of random tiles in random rotations: 3×3 tiles for 2 players up to 4×5 for 5.',
    example: 'A 2-player map has 9 tiles; your restaurant and house 18 can be on the same tile or several tiles apart.',
    related: ['tile_border', 'road', 'distance'],
    rule: R.mapStructure,
    aliases: ['tile', 'map'],
  },
  {
    id: 'tile_border',
    term: 'Tile border',
    group: 'board',
    short: 'The edge between two map tiles. Distance and range are counted in borders crossed, not in squares.',
    example: 'A road that runs from tile A1 into A2 crosses 1 border; a long winding road inside one tile crosses none.',
    related: ['distance', 'range', 'map_tile'],
    rule: R.geometry,
    aliases: ['border', 'seam'],
  },
  {
    id: 'road',
    term: 'Road',
    group: 'board',
    short: 'Roads connect restaurants to houses and suppliers. Any two road squares side by side are connected, even across a tile border, but diagonal never counts.',
    example: 'A house with no road to your restaurant can never buy from you, however close it looks.',
    related: ['distance', 'range', 'bridge'],
    rule: R.roads,
  },
  {
    id: 'bridge',
    term: 'Bridge',
    group: 'board',
    short: 'A road crossing where one road goes over the other. A route goes straight across a bridge square and cannot turn there.',
    example: 'Coming from the north on a bridge tile you can only continue south, not turn east.',
    related: ['road', 'distance'],
    rule: R.roads,
    aliases: ['overpass'],
  },
  {
    id: 'distance',
    term: 'Distance',
    group: 'board',
    short: 'The fewest tile borders crossed along roads from a restaurant entrance to a house (same tile and connected is 0). At Dinnertime each border adds $1 to your price.',
    example: 'Your entrance is on A1 and house 18 is on A2: distance 1. Bo’s path goes C2 → B2 → A2: distance 2.',
    related: ['tile_border', 'unit_price', 'winning_a_sale', 'range'],
    rule: R.dinner,
  },
  {
    id: 'range',
    term: 'Range',
    group: 'board',
    short: 'How far a card may reach, counted like distance in tile borders along roads from one of your entrances. Range 2 means your tile, the next tile, or the one after.',
    example: 'A Marketing Trainee (range 2) cannot place a billboard 3 borders away; a Campaign Manager (range 3) can.',
    related: ['distance', 'tile_border', 'entrance'],
    rule: R.campaigns,
  },
  {
    id: 'house',
    term: 'House',
    group: 'board',
    short: 'Where your customers live. Houses have numbers that set the Dinnertime order, and they only buy what demand tokens say they want.',
    example: 'House 4 eats before house 18. If house 4 buys your last burger, house 18 cannot buy one from you.',
    related: ['demand', 'garden', 'demand_cap', 'new_house'],
    rule: R.dinner,
  },
  {
    id: 'new_house',
    term: 'New house',
    group: 'board',
    short: 'A house a New Business Developer places during the game. It always comes with a garden and goes anywhere next to a road.',
    example: 'You place house 14 with its garden right next to your restaurant: a 5-demand house that pays double.',
    related: ['new_business_developer', 'garden', 'house'],
    rule: R.newHouses,
    aliases: ['placed house'],
  },
  {
    id: 'garden',
    term: 'Garden',
    group: 'board',
    short: 'A 2×1 green strip attached to a house. A garden house pays double the unit price for every item and holds up to 5 demand instead of 3.',
    example: 'You sell 2 pizzas at $10 to a garden house: 2 × $20 = $40 instead of $20.',
    related: ['house', 'demand_cap', 'new_business_developer', 'unit_price'],
    rule: R.gardens,
  },
  {
    id: 'restaurant',
    term: 'Restaurant',
    group: 'board',
    short: 'Your 2×2 building. Food is sold from restaurants and ranges are counted from them. Each chain has at most 3.',
    example: 'A second restaurant across town makes far-away houses distance 0 or 1 for you.',
    related: ['entrance', 'drive_in', 'coming_soon', 'local_manager', 'regional_manager'],
    rule: R.restaurants,
  },
  {
    id: 'entrance',
    term: 'Entrance',
    group: 'board',
    short: 'The corner of a restaurant with the doors. It must touch a road, and every route and distance starts from it.',
    example: 'Rotating a restaurant so its entrance faces a different road can make a house one border closer.',
    related: ['restaurant', 'drive_in', 'distance', 'range'],
    rule: R.geometry,
    aliases: ['door'],
  },
  {
    id: 'drive_in',
    term: 'Drive-in',
    group: 'board',
    short: 'While a Local or Regional Manager is at work, all your open restaurants get entrances on all four corners until Clean up. Distance is counted from the best corner.',
    example: 'A drive-in sign lets your restaurant reach a road on its far side, cutting house 7’s distance from 2 to 1.',
    related: ['local_manager', 'regional_manager', 'entrance'],
    rule: R.driveIns,
  },
  {
    id: 'coming_soon',
    term: 'Coming soon',
    group: 'board',
    short: 'A restaurant placed by a Local Manager is not open yet: it sells nothing and starts no routes until it opens at Clean up.',
    example: 'You open a new restaurant on your turn; at Dinnertime it does not count, next round it does.',
    related: ['local_manager', 'restaurant', 'cleanup'],
    rule: R.restaurants,
  },
  {
    id: 'drink_source',
    term: 'Drink source',
    group: 'board',
    short: 'A beer, lemonade or soft-drink supplier printed on the map. Cart Operators and Truck Drivers collect from each one their road route passes.',
    example: 'Your Cart Operator drives past a lemonade source and a beer source: 2 lemonades and 2 beers.',
    related: ['buyer_route', 'cart_operator', 'errand_boy', 'beer', 'lemonade', 'soft_drink'],
    rule: R.food,
    aliases: ['supplier', 'source'],
  },
  {
    id: 'buyer_route',
    term: 'Buyer route',
    group: 'board',
    short: 'The path a drink buyer drives from one of your entrances, along roads, up to its range. It collects from every drink source next to the road it uses.',
    example: 'Range 2 from tile A1: you can drive into A2 and then A3, picking up from every source along the way.',
    related: ['drink_source', 'cart_operator', 'truck_driver', 'zeppelin_pilot', 'range'],
    rule: R.food,
    aliases: ['route', 'haul'],
  },
];

// ---------------------------------------------------------------------------
// Dinnertime and marketing
// ---------------------------------------------------------------------------

const DINNER: GlossaryEntry[] = [
  {
    id: 'demand',
    term: 'Demand',
    group: 'dinner',
    short: 'Tokens on a house showing what it wants; only marketing creates them. At Dinnertime the house buys all of it from one chain, or nothing.',
    example: 'House 5 shows 2 burgers and 1 beer. A chain with 2 burgers but no beer cannot sell to it at all.',
    related: ['demand_cap', 'campaign', 'dinnertime', 'winning_a_sale'],
    rule: R.dinner,
    aliases: ['demand tokens'],
  },
  {
    id: 'demand_cap',
    term: 'Demand cap',
    group: 'dinner',
    short: 'A house holds at most 3 demand tokens, or 5 with a garden. A campaign that reaches a full house adds nothing there.',
    example: 'House 18 already shows 3 burgers. Your billboard runs, but house 18 stays at 3; the billboard still loses a duration token.',
    related: ['demand', 'garden', 'campaign'],
    rule: R.marketing,
    aliases: ['cap', 'full house', 'limit'],
  },
  {
    id: 'unit_price',
    term: 'Unit price',
    group: 'dinner',
    short: 'What you charge per item: $10, minus $1 per Pricing Manager and $3 per Discount Manager at work, plus $10 for a Luxuries Manager. There is no minimum.',
    example: 'Two Pricing Managers and one Discount Manager: $10 − 1 − 1 − 3 = $5 per item.',
    related: ['pricing_manager', 'discount_manager', 'luxuries_manager', 'winning_a_sale', 'garden'],
    rule: R.dinner,
    aliases: ['price'],
  },
  {
    id: 'winning_a_sale',
    term: 'Price + distance',
    group: 'dinner',
    short: 'How a house picks a chain: among chains with a road to it and every item it wants, the lowest unit price plus distance wins. You are paid only the unit price.',
    example: 'You: $10 + 1 border = 11. Bo: $9 + 2 borders = 11. A tie, so waitresses decide.',
    related: ['unit_price', 'distance', 'tie_break', 'dinnertime'],
    rule: R.dinner,
    aliases: ['who sells', 'competition'],
  },
  {
    id: 'tie_break',
    term: 'Tie-break',
    group: 'dinner',
    short: 'When price plus distance is equal, the chain with more waitresses at work wins. If that is also equal, the chain earlier in turn order wins.',
    example: 'Both 11; you have 1 waitress and Bo has none: you sell.',
    related: ['waitress', 'turn_order', 'winning_a_sale'],
    rule: R.dinner,
    aliases: ['tie', 'ties'],
  },
  {
    id: 'stock',
    term: 'Stock',
    group: 'dinner',
    short: 'Your food and drinks, shared by all your restaurants. Whatever is unsold at Clean up is thrown away unless you have a freezer.',
    example: 'You made 8 burgers and sold 5; the other 3 are thrown away at Clean up.',
    related: ['freezer', 'cleanup', 'kitchen_trainee'],
    rule: R.food,
    aliases: ['inventory', 'goods'],
  },
  {
    id: 'bankruptcy',
    term: 'Bankruptcy',
    group: 'money',
    short: 'With a price below $0 you pay the bank for every item you sell. A chain that cannot pay what it owes is out of the game at the end of the round.',
    example: 'Price −$2 and 3 items sold: you owe $6. With $4 cash you are bankrupt.',
    related: ['unit_price', 'discount_manager'],
    rule: R.bank,
  },
];

const MARKETING: GlossaryEntry[] = [
  {
    id: 'campaign',
    term: 'Campaign',
    group: 'marketing',
    short: 'An advert a marketeer places on the board for one good. Each Marketing phase it puts 1 demand token on every house it reaches, then loses a duration token.',
    example: 'A burger billboard with duration 2 adds a burger to the house next to it in two Marketing phases, then ends.',
    related: ['billboard', 'mailbox', 'airplane', 'radio', 'duration', 'campaign_number', 'busy_marketeer'],
    rule: R.campaigns,
    aliases: ['advert', 'marketing campaign'],
  },
  {
    id: 'campaign_number',
    term: 'Campaign number',
    group: 'marketing',
    short: 'Every campaign tile has a number, and campaigns run in number order, lowest first. When houses fill up, a low number gets there first.',
    example: 'Radio #2 fills house 8 to its cap before billboard #13 runs, so the billboard adds nothing there.',
    related: ['campaign', 'demand_cap', 'marketing_phase'],
    rule: R.marketing,
    aliases: ['run order'],
  },
  {
    id: 'billboard',
    term: 'Billboard',
    group: 'marketing',
    short: 'The simplest campaign. It sits next to a road and reaches every house (or garden) touching one of its squares side-on.',
    example: 'A billboard on the square beside house 4’s garden reaches house 4; one diagonal to it does not.',
    related: ['campaign', 'marketing_trainee', 'first_billboard'],
    rule: R.marketing,
  },
  {
    id: 'mailbox',
    term: 'Mailbox',
    group: 'marketing',
    short: 'Reaches every house in its block: the area you can reach from it without crossing a road. Roads and the map edge are the walls.',
    example: 'A mailbox inside a ring road reaches every house inside the ring, and none outside it.',
    related: ['campaign', 'campaign_manager'],
    rule: R.marketing,
  },
  {
    id: 'airplane',
    term: 'Airplane',
    group: 'marketing',
    short: 'Placed beside the edge of the map, 1, 3 or 5 squares wide. It reaches every house in the rows or columns it covers, right across the map.',
    example: 'A 3-wide airplane on the north edge covers 3 columns from top to bottom of the town.',
    related: ['campaign', 'brand_manager', 'first_airplane'],
    rule: R.marketing,
  },
  {
    id: 'radio',
    term: 'Radio',
    group: 'marketing',
    short: 'The strongest campaign. It reaches every house on its own tile and the 8 tiles around it.',
    example: 'A radio in the middle tile of a 3×3 map reaches every house in town.',
    related: ['campaign', 'brand_director', 'first_radio'],
    rule: R.marketing,
  },
  {
    id: 'duration',
    term: 'Duration',
    group: 'marketing',
    short: 'How many Marketing phases a campaign runs. You choose 1 up to the marketeer’s maximum; one token comes off after each run, even if it added nothing.',
    example: 'A Campaign Manager may choose up to 3. A duration-3 mailbox runs this round and the next two, then the manager comes back.',
    related: ['campaign', 'busy_marketeer', 'eternal_campaign'],
    rule: R.campaigns,
  },
  {
    id: 'eternal_campaign',
    term: 'Eternal campaign',
    group: 'marketing',
    short: 'A campaign that never ends. After you claim First Billboard Campaign, every campaign you launch is eternal, and its marketeer is busy for the rest of the game with no salary.',
    example: 'Your first billboard is eternal: it adds a burger next door every round until the game ends.',
    related: ['first_billboard', 'busy_marketeer', 'duration'],
    rule: R.campaigns,
    aliases: ['infinite', '∞'],
  },
];

const MONEY: GlossaryEntry[] = [
  {
    id: 'bank',
    term: 'Bank',
    group: 'money',
    short: 'Where all income comes from and salaries go; it starts with $50 per player. When it runs dry during Dinnertime, it breaks.',
    example: 'A 4-player game starts the bank at $200. Every sale takes money out; every salary puts some back.',
    related: ['bank_break', 'reserve_card', 'cash', 'game_end'],
    rule: R.bank,
  },
  {
    id: 'bank_break',
    term: 'Bank break',
    group: 'money',
    short: 'When the bank reaches $0 during Dinnertime. The first time, reserve cards refill it and set new CEO slots; the second time, the game ends after that Dinnertime.',
    example: 'Reserve cards $100, $200, $200: the bank refills with $500 and everyone’s CEO now has 3 slots (two votes for 3).',
    related: ['bank', 'reserve_card', 'ceo_slots', 'game_end'],
    rule: R.bank,
    aliases: ['breaking the bank', 'broke'],
  },
  {
    id: 'reserve_card',
    term: 'Reserve card',
    group: 'money',
    short: 'A secret card chosen at setup: +$100, +$200 or +$300. At the first bank break they are revealed, added to the bank, and vote on CEO slots: 2, 3 or 4.',
    example: 'You pick +$300 (vote: 4 slots). If most players picked the same, everyone’s CEO gets 4 slots after the break.',
    related: ['bank_break', 'ceo_slots', 'first_20'],
    rule: R.reserve,
    aliases: ['reserve', 'goal'],
  },
  {
    id: 'milestone',
    term: 'Milestone',
    group: 'basics',
    short: 'A permanent, mandatory bonus for being first to do something. Everyone who does it in the same round gets it; at Clean up it closes for everyone else.',
    example: 'You and Bo both place your first billboard in round 2: you both claim First Billboard Campaign. Nobody else ever can.',
    related: ['first_billboard', 'first_train', 'first_hire_3', 'cleanup'],
    rule: R.milestones,
    aliases: ['milestones'],
  },
];

// ---------------------------------------------------------------------------
// Food and drinks
// ---------------------------------------------------------------------------

const FOOD: GlossaryEntry[] = [
  {
    id: 'burger',
    term: 'Burger',
    group: 'food',
    short: 'A food made by Kitchen Trainees, Burger Cooks and Burger Chefs. It can be marketed.',
    example: 'A Burger Cook makes 3 burgers a turn; a Burger Chef makes 8.',
    related: ['burger_cook', 'kitchen_trainee', 'first_burger_produced', 'first_burger_marketed'],
    rule: R.food,
    food: 'burger',
  },
  {
    id: 'pizza',
    term: 'Pizza',
    group: 'food',
    short: 'A food made by Kitchen Trainees, Pizza Cooks and Pizza Chefs. It can be marketed.',
    example: 'A Kitchen Trainee makes 1 pizza or 1 burger, your choice each turn.',
    related: ['pizza_cook', 'kitchen_trainee', 'first_pizza_produced', 'first_pizza_marketed'],
    rule: R.food,
    food: 'pizza',
  },
  {
    id: 'beer',
    term: 'Beer',
    group: 'food',
    short: 'A drink. Buyers collect it from beer sources on the map; an Errand Boy can fetch one from anywhere.',
    example: 'Your Truck Driver passes one beer source: 3 beers.',
    related: ['drink_source', 'errand_boy', 'cart_operator', 'first_drink_marketed'],
    rule: R.food,
    food: 'beer',
  },
  {
    id: 'lemonade',
    term: 'Lemonade',
    group: 'food',
    short: 'A drink. Buyers collect it from lemonade sources on the map; an Errand Boy can fetch one from anywhere.',
    example: 'A Cart Operator whose route passes two lemonade sources brings back 4 lemonades.',
    related: ['drink_source', 'errand_boy', 'cart_operator', 'first_lemonade_sold'],
    rule: R.food,
    food: 'lemonade',
  },
  {
    id: 'soft_drink',
    term: 'Soft drink',
    group: 'food',
    short: 'A drink (the cola). Buyers collect it from soft-drink sources on the map; an Errand Boy can fetch one from anywhere.',
    example: 'House 10 wants a soft drink. Without one in stock you cannot sell it anything.',
    related: ['drink_source', 'errand_boy', 'cart_operator', 'first_coke_sold'],
    rule: R.food,
    food: 'soft_drink',
    aliases: ['soda', 'coke', 'cola'],
  },
  {
    id: 'freezer',
    term: 'Freezer',
    group: 'food',
    short: 'Lets you keep up to 10 unsold items at Clean up instead of throwing them away. You get one from the First to Throw Away milestone, usable from the next Clean up.',
    example: 'You made 8 pizzas and sold 3: with a freezer you keep the other 5 for next round.',
    related: ['first_throw_away', 'stock', 'cleanup'],
    rule: R.cleanup,
  },
];

// ---------------------------------------------------------------------------
// Employee cards (base)
// ---------------------------------------------------------------------------

type Emp = Omit<GlossaryEntry, 'group' | 'employee'> & { id: string };
const emp = (e: Emp, employee: EmployeeId, module?: ModuleId): GlossaryEntry => ({ ...e, group: module ? 'ketchup' : 'employee', employee, ...(module ? { module } : {}) });

const EMPLOYEES: GlossaryEntry[] = [
  emp(
    {
      id: 'waitress',
      term: 'Waitress',
      short: 'Entry level, no salary. Earns $3 at the end of every Dinnertime while at work, and wins price ties against chains with fewer waitresses.',
      example: 'Two waitresses at work: +$6 after Dinnertime, even if you sold nothing.',
      related: ['tie_break', 'first_waitress', 'at_work'],
      rule: R.dinner,
    },
    'waitress',
  ),
  emp(
    {
      id: 'management_trainee',
      term: 'Management Trainee',
      short: 'Entry-level manager with 2 slots, no salary. The start of the whole management career line.',
      example: 'In a CEO slot it turns that one slot into two: CEO → Management Trainee → Waitress + Errand Boy.',
      related: ['manager', 'junior_vp', 'new_business_developer', 'luxuries_manager'],
      rule: R.career,
    },
    'management_trainee',
  ),
  emp(
    {
      id: 'junior_vp',
      term: 'Junior Vice President',
      short: 'Manager with 3 slots, salary $5. Trained from a Management Trainee; trains into many specialists.',
      example: 'Train it next into a Vice President (4 slots), or into a Local Manager, Discount Manager, Recruiting Manager or Coach.',
      related: ['manager', 'management_trainee', 'vice_president'],
      rule: R.career,
      aliases: ['jvp'],
    },
    'junior_vp',
  ),
  emp(
    {
      id: 'vice_president',
      term: 'Vice President',
      short: 'Manager with 4 slots, salary $5. Trained from a Junior VP.',
      example: 'Train it into a Senior VP, a Regional Manager or a Guru.',
      related: ['manager', 'junior_vp', 'senior_vp'],
      rule: R.career,
      aliases: ['vp'],
    },
    'vice_president',
  ),
  emp(
    {
      id: 'senior_vp',
      term: 'Senior Vice President',
      short: 'Manager with 5 slots, salary $5. Trained from a Vice President.',
      example: 'Its 5 slots let one CEO slot carry five workers. It trains into the CFO, HR Director or Executive VP.',
      related: ['manager', 'vice_president', 'executive_vp', 'cfo', 'hr_director'],
      rule: R.career,
      aliases: ['svp'],
    },
    'senior_vp',
  ),
  emp(
    {
      id: 'executive_vp',
      term: 'Executive Vice President',
      short: 'Manager with 10 slots, salary $5, 1x. The top of the management line.',
      example: 'CEO → Executive VP → ten workers: a huge company from a single CEO slot.',
      related: ['manager', 'senior_vp', 'one_x'],
      rule: R.career,
      aliases: ['evp'],
    },
    'executive_vp',
  ),
  emp(
    {
      id: 'new_business_developer',
      term: 'New Business Developer',
      short: 'Salary $5. Places a new house with its garden anywhere next to a road, or adds a garden to a house that has none.',
      example: 'Add a garden to house 18 next to your restaurant: it now pays double and holds 5 demand.',
      related: ['new_house', 'garden', 'management_trainee'],
      rule: R.houses,
      aliases: ['nbd'],
    },
    'new_business_developer',
  ),
  emp(
    {
      id: 'luxuries_manager',
      term: 'Luxuries Manager',
      short: 'Salary $5, 1x. Raises your unit price by $10 while at work (mandatory): fewer houses pick you, but each sale pays much more.',
      example: 'Price $20 to a garden house: each item pays $40.',
      related: ['unit_price', 'mandatory', 'management_trainee'],
      rule: R.dinner,
    },
    'luxuries_manager',
  ),
  emp(
    {
      id: 'pricing_manager',
      term: 'Pricing Manager',
      short: 'Entry level, no salary, cannot be trained. Lowers your unit price by $1 while at work (mandatory).',
      example: 'Price $9 + distance 1 = 10 beats Bo’s $10 + 1 = 11.',
      related: ['unit_price', 'discount_manager', 'first_lower_prices'],
      rule: R.dinner,
    },
    'pricing_manager',
  ),
  emp(
    {
      id: 'discount_manager',
      term: 'Discount Manager',
      short: 'Salary $5. Lowers your unit price by $3 while at work (mandatory). Trained from a Junior VP.',
      example: 'With a Discount Manager you sell at $7, and win houses 2 borders further away than Bo at $10.',
      related: ['unit_price', 'pricing_manager', 'first_lower_prices', 'junior_vp'],
      rule: R.dinner,
    },
    'discount_manager',
  ),
  emp(
    {
      id: 'local_manager',
      term: 'Local Manager',
      short: 'Salary $5. Places a new restaurant (coming soon) within road range 3 of an open one, and gives your restaurants drive-ins while at work.',
      example: 'Your second restaurant opens at Clean up, two tiles closer to the busy side of town.',
      related: ['restaurant', 'coming_soon', 'drive_in', 'regional_manager'],
      rule: R.restaurants,
    },
    'local_manager',
  ),
  emp(
    {
      id: 'regional_manager',
      term: 'Regional Manager',
      short: 'Salary $5, 1x. Places an open restaurant anywhere next to a road, or moves one of yours. Gives drive-ins while at work.',
      example: 'Move your quiet restaurant across the map next to three garden houses; it sells this Dinnertime.',
      related: ['restaurant', 'drive_in', 'local_manager', 'vice_president'],
      rule: R.restaurants,
    },
    'regional_manager',
  ),
  emp(
    {
      id: 'cfo',
      term: 'CFO',
      short: 'Salary $5, 1x. Adds 50% (rounded up) to all the cash you earn in Dinnertime, including waitress tips and bonuses.',
      example: 'You earn $45 at Dinnertime: the CFO adds $23, for $68.',
      related: ['first_100', 'senior_vp', 'mandatory'],
      rule: R.dinner,
      aliases: ['chief financial officer'],
    },
    'cfo',
  ),
  emp(
    {
      id: 'recruiting_girl',
      term: 'Recruiting Girl',
      short: 'Entry level, no salary, cannot be trained. Hires 1 extra person.',
      example: 'CEO + Recruiting Girl = 2 hires this turn.',
      related: ['hiring', 'recruiting_manager', 'first_hire_3'],
      rule: R.recruit,
    },
    'recruiting_girl',
  ),
  emp(
    {
      id: 'recruiting_manager',
      term: 'Recruiting Manager',
      short: 'Salary $5. Two actions: each one hires a person, or, if unused, saves $5 of salary at Payday.',
      example: 'Hire one Waitress and keep the other action: $5 off this Payday.',
      related: ['hiring', 'salary', 'hr_director', 'junior_vp'],
      rule: R.recruit,
    },
    'recruiting_manager',
  ),
  emp(
    {
      id: 'hr_director',
      term: 'HR Director',
      short: 'Salary $5, 1x. Four actions: each one hires a person or, if unused, saves $5 of salary at Payday.',
      example: 'Hire 1, keep 3: $15 off your salaries this round.',
      related: ['hiring', 'recruiting_manager', 'salary', 'senior_vp'],
      rule: R.recruit,
    },
    'hr_director',
  ),
  emp(
    {
      id: 'trainer',
      term: 'Trainer',
      short: 'Entry level, no salary, cannot be trained. Trains one beach card one step.',
      example: 'Hire a Kitchen Trainee, then train it into a Burger Cook in the same turn.',
      related: ['training', 'coach', 'guru', 'first_train'],
      rule: R.train,
    },
    'trainer',
  ),
  emp(
    {
      id: 'coach',
      term: 'Coach',
      short: 'Salary $5. Two training actions; may use both on the same card to move it two steps.',
      example: 'Errand Boy → Cart Operator → Truck Driver in one go.',
      related: ['training', 'trainer', 'guru', 'junior_vp'],
      rule: R.train,
    },
    'coach',
  ),
  emp(
    {
      id: 'guru',
      term: 'Guru',
      short: 'Salary $5, 1x. Three training actions; may move one card up to three steps.',
      example: 'Marketing Trainee → Campaign Manager → Brand Manager → Brand Director in one turn.',
      related: ['training', 'coach', 'trainer', 'vice_president'],
      rule: R.train,
    },
    'guru',
  ),
  emp(
    {
      id: 'errand_boy',
      term: 'Errand Boy',
      short: 'Entry level, no salary. Fetches 1 drink of any type, no route needed.',
      example: 'House 8 wants a beer and there is no beer source near you: send the Errand Boy.',
      related: ['beer', 'lemonade', 'soft_drink', 'cart_operator', 'first_errand_boy'],
      rule: R.food,
    },
    'errand_boy',
  ),
  emp(
    {
      id: 'cart_operator',
      term: 'Cart Operator',
      short: 'Salary $5. Drives a road route of range 2 from one of your entrances and collects 2 drinks from every drink source it passes.',
      example: 'Route past a beer and a lemonade source: 2 beers + 2 lemonades.',
      related: ['buyer_route', 'drink_source', 'truck_driver', 'first_cart_operator'],
      rule: R.food,
    },
    'cart_operator',
  ),
  emp(
    {
      id: 'truck_driver',
      term: 'Truck Driver',
      short: 'Salary $5. Road route of range 3; collects 3 drinks from every source it passes.',
      example: 'Two soft-drink sources on the way: 6 soft drinks.',
      related: ['buyer_route', 'cart_operator', 'zeppelin_pilot'],
      rule: R.food,
    },
    'truck_driver',
  ),
  emp(
    {
      id: 'zeppelin_pilot',
      term: 'Zeppelin Pilot',
      short: 'Salary $5, 1x. Flies tile to tile ignoring roads, up to 4 borders, and collects 2 from every source on every tile it enters, including the start tile.',
      example: 'Fly across 4 tiles holding 3 sources: 6 drinks, no roads needed.',
      related: ['buyer_route', 'truck_driver', 'drink_source'],
      rule: R.food,
    },
    'zeppelin_pilot',
  ),
  emp(
    {
      id: 'marketing_trainee',
      term: 'Marketing Trainee',
      short: 'Entry level, no salary. Places a billboard within road range 2, for up to 2 Marketing phases.',
      example: 'A burger billboard next to house 18 with duration 2: two burgers of demand over two rounds.',
      related: ['billboard', 'campaign', 'campaign_manager', 'first_billboard'],
      rule: R.campaigns,
    },
    'marketing_trainee',
  ),
  emp(
    {
      id: 'campaign_manager',
      term: 'Campaign Manager',
      short: 'Salary $5. Places a mailbox or billboard within road range 3, duration up to 3.',
      example: 'A pizza mailbox inside a block with 3 houses: 3 pizzas of demand every round for 3 rounds.',
      related: ['mailbox', 'billboard', 'marketing_trainee', 'brand_manager'],
      rule: R.campaigns,
    },
    'campaign_manager',
  ),
  emp(
    {
      id: 'brand_manager',
      term: 'Brand Manager',
      short: 'Salary $5. Places an airplane, mailbox or billboard anywhere (no range), duration up to 4.',
      example: 'A 5-wide beer airplane along the edge reaches every house in five columns.',
      related: ['airplane', 'campaign_manager', 'brand_director', 'first_airplane'],
      rule: R.campaigns,
    },
    'brand_manager',
  ),
  emp(
    {
      id: 'brand_director',
      term: 'Brand Director',
      short: 'Salary $5, 1x. Places a radio, airplane, mailbox or billboard anywhere (no range), duration up to 5.',
      example: 'A radio reaches 9 tiles of houses for 5 rounds.',
      related: ['radio', 'brand_manager', 'first_radio'],
      rule: R.campaigns,
    },
    'brand_director',
  ),
  emp(
    {
      id: 'kitchen_trainee',
      term: 'Kitchen Trainee',
      short: 'Entry level, no salary. Makes 1 burger or 1 pizza.',
      example: 'Not much on its own, but train it and it becomes a Burger Cook (3 burgers) or Pizza Cook (3 pizzas).',
      related: ['burger', 'pizza', 'burger_cook', 'pizza_cook'],
      rule: R.food,
    },
    'kitchen_trainee',
  ),
  emp(
    {
      id: 'burger_cook',
      term: 'Burger Cook',
      short: 'Salary $5. Makes 3 burgers. If you produce, you make all 3.',
      example: 'Two Burger Cooks: 6 burgers this round.',
      related: ['burger', 'kitchen_trainee', 'burger_chef', 'first_burger_produced'],
      rule: R.food,
    },
    'burger_cook',
  ),
  emp(
    {
      id: 'burger_chef',
      term: 'Burger Chef',
      short: 'Salary $5, 1x. Makes 8 burgers.',
      example: 'Enough burgers to feed three or four houses in one Dinnertime.',
      related: ['burger', 'burger_cook'],
      rule: R.food,
    },
    'burger_chef',
  ),
  emp(
    {
      id: 'pizza_cook',
      term: 'Pizza Cook',
      short: 'Salary $5. Makes 3 pizzas.',
      example: 'A Pizza Cook plus a Kitchen Trainee: 4 pizzas.',
      related: ['pizza', 'kitchen_trainee', 'pizza_chef', 'first_pizza_produced'],
      rule: R.food,
    },
    'pizza_cook',
  ),
  emp(
    {
      id: 'pizza_chef',
      term: 'Pizza Chef',
      short: 'Salary $5, 1x. Makes 8 pizzas.',
      example: 'Eight pizzas a round lets you serve every pizza house in reach.',
      related: ['pizza', 'pizza_cook'],
      rule: R.food,
    },
    'pizza_chef',
  ),
];

// ---------------------------------------------------------------------------
// Milestones (base)
// ---------------------------------------------------------------------------

type Ms = Omit<GlossaryEntry, 'group' | 'milestone'>;
const ms = (e: Ms, milestone: MilestoneId, module?: ModuleId): GlossaryEntry => ({ ...e, group: module ? 'ketchup' : 'milestone', milestone, ...(module ? { module } : {}) });

const MILESTONES: GlossaryEntry[] = [
  ms(
    {
      id: 'first_billboard',
      term: 'First Billboard Campaign',
      short: 'Launch a billboard. From then on your Campaign Managers, Brand Managers and Brand Director cost no salary, and every campaign you launch is eternal.',
      example: 'Your billboard and every later campaign never run out, but those marketeers are busy for good.',
      related: ['billboard', 'eternal_campaign', 'busy_marketeer', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_billboard',
  ),
  ms(
    {
      id: 'first_train',
      term: 'First to Train an Employee',
      short: 'Train anyone. You pay $15 less salary every Payday (never below $0).',
      example: 'You owe $20 in salaries: you pay $5.',
      related: ['training', 'salary', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_train',
  ),
  ms(
    {
      id: 'first_hire_3',
      term: 'First to Hire 3 Employees in 1 Turn',
      short: 'Hire 3 or more people in one turn (the CEO’s hire counts). You immediately get 2 free Management Trainees.',
      example: 'CEO + 2 Recruiting Girls hire 3; two Management Trainees join your beach as well.',
      related: ['hiring', 'management_trainee', 'recruiting_girl', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_hire_3',
  ),
  ms(
    {
      id: 'first_burger_marketed',
      term: 'First Burger Marketed',
      short: 'Launch a burger campaign. You earn $5 extra for every burger you sell (not doubled by gardens).',
      example: 'Sell 2 burgers at $10 to a garden house: $40 + $10 = $50.',
      related: ['burger', 'campaign', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_burger_marketed',
  ),
  ms(
    {
      id: 'first_pizza_marketed',
      term: 'First Pizza Marketed',
      short: 'Launch a pizza campaign. You earn $5 extra for every pizza you sell.',
      example: 'Sell 3 pizzas at $9: $27 + $15 = $42.',
      related: ['pizza', 'campaign', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_pizza_marketed',
  ),
  ms(
    {
      id: 'first_drink_marketed',
      term: 'First Drink Marketed',
      short: 'Launch a campaign for any drink. You earn $5 extra for every drink you sell, of every type.',
      example: 'Market lemonade, then sell 2 beers: +$10 on top of their price.',
      related: ['beer', 'lemonade', 'soft_drink', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_drink_marketed',
  ),
  ms(
    {
      id: 'first_errand_boy',
      term: 'First Errand Boy Played',
      short: 'Have an Errand Boy at work. Errand Boys now fetch 2 drinks of one type; Cart Operators and Zeppelins collect 3 per source, Truck Drivers 4.',
      example: 'Your Cart Operator passes 2 sources: 6 drinks instead of 4.',
      related: ['errand_boy', 'cart_operator', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_errand_boy',
  ),
  ms(
    {
      id: 'first_20',
      term: 'First to Have $20',
      short: 'Reach $20 cash in Dinnertime. You may look at everyone’s secret reserve cards from now on.',
      example: 'You see the others picked $300 and $300: CEOs will probably get 4 slots after the first break.',
      related: ['reserve_card', 'bank_break', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_20',
  ),
  ms(
    {
      id: 'first_burger_produced',
      term: 'First Burger Produced',
      short: 'Make a burger. You immediately get a free Burger Cook on the beach (you must pay or fire it at Payday).',
      example: 'Your Kitchen Trainee makes 1 burger, and a Burger Cook joins you for next round.',
      related: ['burger', 'burger_cook', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_burger_produced',
  ),
  ms(
    {
      id: 'first_pizza_produced',
      term: 'First Pizza Produced',
      short: 'Make a pizza. You immediately get a free Pizza Cook on the beach (you must pay or fire it at Payday).',
      example: 'Make 1 pizza in round 2 and start round 3 with a Pizza Cook ready to work.',
      related: ['pizza', 'pizza_cook', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_pizza_produced',
  ),
  ms(
    {
      id: 'first_waitress',
      term: 'First Waitress Played',
      short: 'Have a Waitress at work. Each of your waitresses now earns $5 at Dinnertime instead of $3.',
      example: 'Two waitresses: $10 after every Dinnertime.',
      related: ['waitress', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_waitress',
  ),
  ms(
    {
      id: 'first_throw_away',
      term: 'First to Throw Away Food or Drink',
      short: 'Throw away at least one unsold item at Clean up. You get a freezer, usable from the next Clean up.',
      example: 'You throw away 2 burgers this round; next round you can keep up to 10 items.',
      related: ['freezer', 'cleanup', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_throw_away',
  ),
  ms(
    {
      id: 'first_lower_prices',
      term: 'First to Lower Prices',
      short: 'Start a Dinnertime with a Pricing or Discount Manager at work. Your unit price is $1 lower for the rest of the game.',
      example: 'Even with no pricing cards at work later, you sell at $9.',
      related: ['unit_price', 'pricing_manager', 'discount_manager', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_lower_prices',
  ),
  ms(
    {
      id: 'first_cart_operator',
      term: 'First Cart Operator Played',
      short: 'Have a Cart Operator at work. Your Cart Operators, Truck Drivers and Zeppelin Pilots get +1 range.',
      example: 'Your Cart Operator now drives range 3, reaching a lemonade source two tiles away.',
      related: ['cart_operator', 'range', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_cart_operator',
  ),
  ms(
    {
      id: 'first_airplane',
      term: 'First Airplane Campaign',
      short: 'Launch an airplane. You count 2 extra open slots when choosing turn order (they cannot hold cards).',
      example: 'You have 1 open slot and Bo has 2: with the milestone you have 3 and choose first.',
      related: ['airplane', 'open_slots', 'turn_order', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_airplane',
  ),
  ms(
    {
      id: 'first_radio',
      term: 'First Radio Campaign',
      short: 'Launch a radio. Your radios now add 2 demand per house instead of 1 (as far as the cap allows).',
      example: 'Your radio reaches 6 houses: up to 12 demand each Marketing phase.',
      related: ['radio', 'demand', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_radio',
  ),
  ms(
    {
      id: 'first_100',
      term: 'First to Have $100',
      short: 'Reach $100 cash in Dinnertime. From the next Dinnertime your CEO gives the CFO bonus (+50%); you must fire a CFO if you have one and can never train one.',
      example: 'You earn $60 next Dinnertime: the CEO adds $30.',
      related: ['cfo', 'ceo', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_100',
  ),
  ms(
    {
      id: 'first_pay_20',
      term: 'First to Pay $20 or More in Salaries',
      short: 'Pay $20 or more at Payday after discounts. From next round you may stack training from several trainers on one card.',
      example: 'Two Trainers and a Coach on one Management Trainee: four steps, straight to Executive VP.',
      related: ['training', 'salary', 'trainer', 'milestone'],
      rule: R.milestoneTable,
    },
    'first_pay_20',
  ),
];

// ---------------------------------------------------------------------------
// Ketchup expansion
// ---------------------------------------------------------------------------

const K = 'ketchup' as const;
const mod = (e: Omit<GlossaryEntry, 'group'>): GlossaryEntry => ({ ...e, group: K });

const KETCHUP_CONCEPTS: GlossaryEntry[] = [
  mod({
    id: 'ketchup_expansion',
    term: 'Ketchup expansion',
    short: 'The Ketchup Mechanism & Other Ideas: 17 optional modules that add foods, cards, map pieces and milestones. Each works alone or combined.',
    example: 'Turn on Kimchi and Fry Chefs only, and everything else plays like the base game.',
    related: ['module_kimchi', 'module_coffee', 'module_new_milestones', 'module_lobbyists'],
    rule: R.kModules,
    aliases: ['modules', 'expansion'],
  }),
  mod({
    id: 'used_card',
    term: 'Used (vs played)',
    short: 'With New Milestones, most milestones need a card to be used: at least one of its effects actually happens. Being at work (played) is not enough.',
    example: 'A Marketing Trainee at work who places no campaign is played but not used: no First Marketing Trainee Used.',
    related: ['module_new_milestones', 'at_work'],
    rule: R.kMilestones,
    module: 'ketchup:newMilestones',
    aliases: ['used'],
  }),
  mod({
    id: 'apartment',
    term: 'Apartment',
    short: 'A big building on the New Districts tiles. Every marketing token placed there is doubled, it has no demand cap and it can never have a garden.',
    example: 'A billboard reaches the π apartment: 2 burgers instead of 1, and it can keep piling up.',
    related: ['module_new_districts', 'demand_cap', 'house'],
    rule: R.kDistricts,
    module: 'ketchup:newDistricts',
  }),
  mod({
    id: 'coffee',
    term: 'Coffee',
    short: 'Made by baristas; it is not a drink and cannot be marketed or frozen. Houses buy 1 coffee from each coffee shop or restaurant with coffee they pass on the way to dinner.',
    example: 'House 18 walks to Bo’s restaurant past your coffee shop: you sell 1 coffee.',
    related: ['coffee_shop', 'barista_trainee', 'module_coffee'],
    rule: R.kCoffee,
    module: 'ketchup:coffee',
    food: 'coffee',
  }),
  mod({
    id: 'coffee_shop',
    term: 'Coffee shop',
    short: 'A 1×1 shop with doors on every side, placed when you train a barista; at most one per tile. It sells only coffee and counts as a starting point for your ranges.',
    example: 'Your coffee shop on the far side of town lets your Cart Operator start its route from there.',
    related: ['coffee', 'barista', 'module_coffee'],
    rule: R.kCoffee,
    module: 'ketchup:coffee',
  }),
  mod({
    id: 'kimchi',
    term: 'Kimchi',
    short: 'Made by the Kimchi Master at Clean up. At Dinnertime a chain that has kimchi beats every chain without, whatever the price, and sells exactly 1 kimchi as well.',
    example: 'Bo at $12 with kimchi beats you at $11 without: Bo sells the order plus 1 kimchi.',
    related: ['kimchi_master', 'food_priority', 'module_kimchi'],
    rule: R.kKimchi,
    module: 'ketchup:kimchi',
    food: 'kimchi',
  }),
  mod({
    id: 'sushi',
    term: 'Sushi',
    short: 'Garden houses prefer a chain that can give them sushi for every demand token, instead of what they asked for. All or nothing.',
    example: 'A garden house wants a burger and a beer; you have 2 sushi: you sell 2 sushi at double price.',
    related: ['sushi_cook', 'garden', 'food_priority', 'module_sushi'],
    rule: R.kSushi,
    module: 'ketchup:sushi',
    food: 'sushi',
  }),
  mod({
    id: 'noodles',
    term: 'Noodles',
    short: 'If nobody can serve a house what it wants, it takes noodles instead: one per demand token, from a chain with enough.',
    example: 'House 18 wants burger, pizza and beer, and nobody has all three. You have 3 noodles: you sell.',
    related: ['noodle_cook', 'food_priority', 'module_noodles'],
    rule: R.kNoodles,
    module: 'ketchup:noodles',
    food: 'noodles',
  }),
  mod({
    id: 'food_priority',
    term: 'Food priority (kimchi, sushi, noodles)',
    short: 'With these foods, a house picks a tier first and only then compares price + distance inside it: kimchi beats sushi, sushi beats the exact order, and noodles come last.',
    example: 'Garden house: sushi + kimchi > exact order + kimchi > noodles + kimchi > sushi > exact order > noodles.',
    related: ['kimchi', 'sushi', 'noodles', 'winning_a_sale'],
    rule: R.kPriority,
    module: 'ketchup:noodles',
    aliases: ['tiers'],
  }),
  mod({
    id: 'park',
    term: 'Park',
    short: 'A green space a Lobbyist places. Houses next to it pay double, or triple if they also have a garden; distance and demand do not change.',
    example: 'A garden house beside a park buys 2 burgers at $10: 2 × $30 = $60.',
    related: ['lobbyist', 'garden', 'module_lobbyists'],
    rule: R.kLobbyists,
    module: 'ketchup:lobbyists',
  }),
  mod({
    id: 'lobbyist_road',
    term: 'Lobbyist road',
    short: 'A road tile a Lobbyist builds. It stays under construction until Clean up (nothing may use it yet), then becomes a normal road.',
    example: 'Your new road links your restaurant to a lemonade source; from next round your Cart Operator can drive it.',
    related: ['lobbyist', 'roadworks', 'module_lobbyists'],
    rule: R.kLobbyists,
    module: 'ketchup:lobbyists',
  }),
  mod({
    id: 'roadworks',
    term: 'Roadworks',
    short: 'Cones where a new road joins an existing one. Until Clean up, any route through roadworks costs +1 distance.',
    example: 'Your route to house 7 passes roadworks this round: distance 1 becomes 2.',
    related: ['lobbyist_road', 'distance', 'module_lobbyists'],
    rule: R.kLobbyists,
    module: 'ketchup:lobbyists',
  }),
  mod({
    id: 'rural_area',
    term: 'Rural area',
    short: 'A countryside tile beside the map that behaves like a house with no demand cap. It always eats last and is reached only through a freeway.',
    example: 'Two giant billboards put 4 demand on the rural area every round; whoever reaches it via the freeway cheapest sells it all.',
    related: ['giant_billboard', 'freeway', 'module_rural_marketeers'],
    rule: R.kRural,
    module: 'ketchup:ruralMarketeers',
  }),
  mod({
    id: 'freeway',
    term: 'Freeway',
    short: 'A link from the edge of the map to the rural area, placed by whoever first uses a Rural Marketeer. Without one, nobody can sell to the rural area.',
    example: 'You place the freeway next to your tile, so the rural area is distance 0 for you.',
    related: ['rural_area', 'first_rural_marketeer_used'],
    rule: R.kRural,
    module: 'ketchup:ruralMarketeers',
  }),
  mod({
    id: 'giant_billboard',
    term: 'Giant billboard',
    short: 'A Rural Marketeer’s campaign beside the rural area. Always eternal; it adds 2 tokens of its good to the rural area every Marketing phase.',
    example: 'A pizza giant billboard: +2 pizzas on the rural area each round, forever.',
    related: ['rural_area', 'rural_marketeer', 'eternal_campaign'],
    rule: R.kRural,
    module: 'ketchup:ruralMarketeers',
  }),
  mod({
    id: 'gourmet_guide',
    term: 'Gourmet guide',
    short: 'A Gourmet Food Critic’s campaign, set beside the board. It adds 1 demand to every house with a garden (not apartments or the rural area).',
    example: 'Four garden houses on the map: a burger guide adds a burger to all four.',
    related: ['gourmet_food_critic', 'garden', 'campaign'],
    rule: R.kGourmet,
    module: 'ketchup:gourmetCritics',
  }),
  mod({
    id: 'remove_after_round',
    term: 'Until round N',
    short: 'Some milestones vanish if nobody claims them in time: at the Clean up of that round they are crossed out for everyone.',
    example: 'With Hard Choices, First Burger Marketed shows "Until round 2": claim it in rounds 1–2 or never.',
    related: ['module_hard_choices', 'milestone'],
    rule: R.kHard,
    module: 'ketchup:hardChoices',
    aliases: ['hard choices token'],
  }),
];

const MODULES: GlossaryEntry[] = [
  mod({ id: 'module_new_districts', term: 'New Districts (module)', short: 'Adds five map tiles: three lemonade sources on one, two houses on another, a house with a printed garden, and two apartments.', example: 'An apartment drops 2 tokens per marketing event and has no cap.', related: ['apartment', 'ketchup_expansion'], rule: R.kDistricts, module: 'ketchup:newDistricts' }),
  mod({ id: 'module_lobbyists', term: 'Lobbyists (module)', short: 'Adds the Lobbyist, who builds roads and parks, plus roadworks and the First Lobbyist Used milestone.', example: 'A new road can connect your restaurant to houses that had no route to you.', related: ['lobbyist', 'park', 'lobbyist_road', 'roadworks'], rule: R.kLobbyists, module: 'ketchup:lobbyists' }),
  mod({ id: 'module_new_milestones', term: 'New Milestones (module)', short: 'Replaces all 18 base milestones with 17 new ones, mostly for being first to use a card. Three of them vanish after round 2.', example: 'First Burger Sold gives your CEO 4 slots for the rest of the game.', related: ['used_card', 'first_marketeer_used', 'first_burger_sold'], rule: R.kMilestones, module: 'ketchup:newMilestones' }),
  mod({ id: 'module_coffee', term: 'Coffee (module)', short: 'Adds baristas, coffee and coffee shops. Houses buy coffee on their way to dinner.', example: 'Training a Barista Trainee places a coffee shop on the board.', related: ['coffee', 'coffee_shop', 'barista_trainee'], rule: R.kCoffee, module: 'ketchup:coffee' }),
  mod({ id: 'module_kimchi', term: 'Kimchi (module)', short: 'Adds the Kimchi Master and kimchi, which makes houses prefer you regardless of price.', example: 'One kimchi in stock can win you a house you are $3 too expensive for.', related: ['kimchi', 'kimchi_master'], rule: R.kKimchi, module: 'ketchup:kimchi' }),
  mod({ id: 'module_sushi', term: 'Sushi (module)', short: 'Adds Sushi Cooks and Chefs. Garden houses would rather eat sushi than what they asked for.', example: 'Two sushi win a garden house that wants burger + beer.', related: ['sushi', 'sushi_cook'], rule: R.kSushi, module: 'ketchup:sushi' }),
  mod({ id: 'module_noodles', term: 'Noodles (module)', short: 'Adds Noodle Cooks and Chefs. Noodles feed houses nobody else can serve.', example: 'A Noodle Cook makes 6 noodles: a safety net for awkward orders.', related: ['noodles', 'noodle_cook'], rule: R.kNoodles, module: 'ketchup:noodles' }),
  mod({ id: 'module_ketchup', term: 'Ketchup (module)', short: 'Adds the Ketchup milestone: if someone else sells to demand your marketing created, you get a permanent −$1 at Dinnertime.', example: 'Bo sells to a house your billboard filled; you claim Ketchup at the end of Dinnertime.', related: ['ketchup_milestone'], rule: R.kKetchup, module: 'ketchup:ketchup' }),
  mod({ id: 'module_fry_chefs', term: 'Fry Chefs (module)', short: 'Adds the Fry Chef: +$10 for every house you sell to.', example: 'Two Fry Chefs and one sale: +$20.', related: ['fry_chef'], rule: R.kFry, module: 'ketchup:fryChefs' }),
  mod({ id: 'module_night_shift', term: 'Night Shift Managers (module)', short: 'Adds the Night Shift Manager, who makes your salary-free cards work twice.', example: 'Your Waitress earns $6 and counts as two waitresses for ties.', related: ['night_shift_manager'], rule: R.kNight, module: 'ketchup:nightShift' }),
  mod({ id: 'module_mass_marketeers', term: 'Mass Marketeers (module)', short: 'Adds the Mass Marketeer: each one at work makes every campaign run an extra time in Marketing.', example: 'One Mass Marketeer anywhere: all campaigns run twice this round, losing only one duration token.', related: ['mass_marketeer'], rule: R.kMass, module: 'ketchup:massMarketeers' }),
  mod({ id: 'module_rural_marketeers', term: 'Rural Marketeers (module)', short: 'Adds the rural area, giant billboards, freeways and the Rural Marketeer.', example: 'The rural area can soak up huge orders every round.', related: ['rural_area', 'giant_billboard', 'freeway', 'rural_marketeer'], rule: R.kRural, module: 'ketchup:ruralMarketeers' }),
  mod({ id: 'module_gourmet_critics', term: 'Gourmet Food Critics (module)', short: 'Adds the Gourmet Food Critic, whose guide markets to every garden house at once.', example: 'One guide can reach houses all over the map.', related: ['gourmet_food_critic', 'gourmet_guide'], rule: R.kGourmet, module: 'ketchup:gourmetCritics' }),
  mod({ id: 'module_movie_stars', term: 'Movie Stars (module)', short: 'Waitresses can train into B, C or D Movie Stars, who choose turn order before everyone and win waitress ties.', example: 'With a B-Movie Star at work you always pick your turn position first.', related: ['b_movie_star', 'c_movie_star', 'd_movie_star'], rule: R.kStars, module: 'ketchup:movieStars' }),
  mod({ id: 'module_reserve_prices', term: 'Reserve Prices (module)', short: 'Every reserve card is +$200 and votes on a new base price ($5, $10 or $20) instead of CEO slots.', example: 'Two $20 cards and one $5: after the break the base price is $20.', related: ['reserve_card', 'unit_price', 'bank_break'], rule: R.kReserve, module: 'ketchup:reservePrices' }),
  mod({ id: 'module_hard_choices', term: 'Hard Choices (module)', short: 'Five base milestones vanish if unclaimed: the three "marketed" ones and First to Train after round 2, Hire 3 after round 3.', example: 'Nobody marketed pizza by the end of round 2: First Pizza Marketed is gone.', related: ['remove_after_round', 'first_burger_marketed', 'first_hire_3'], rule: R.kHard, module: 'ketchup:hardChoices' }),
  mod({ id: 'module_six_players', term: 'Six Players (module)', short: 'Adds a sixth chain (Siap Faji) and a 4×6 map. Requires New Districts.', example: 'Six players: three copies of every 1x card, a $300 bank.', related: ['module_new_districts', 'one_x'], rule: R.kSix, module: 'ketchup:sixPlayers' }),
];

const KETCHUP_EMPLOYEES: GlossaryEntry[] = [
  emp({ id: 'fry_chef', term: 'Fry Chef', short: 'Salary $5. Trained from any cook, it adds $10 to every sale while at work: once per house, not per item, coffee included.', example: '3 burgers at $20 with two Fry Chefs at work: $60 + $20 = $80.', related: ['module_fry_chefs', 'burger_cook', 'pizza_cook'], rule: R.kFry }, 'ketchup:fry_chef', 'ketchup:fryChefs'),
  emp({ id: 'kimchi_master', term: 'Kimchi Master', short: 'Entry level, salary $5, 1x. Makes 1 kimchi at the end of every Clean up, which you keep for next round.', example: 'Next Dinnertime that kimchi makes one house pick you over a cheaper rival.', related: ['kimchi', 'module_kimchi'], rule: R.kKimchi }, 'ketchup:kimchi_master', 'ketchup:kimchi'),
  emp({ id: 'sushi_cook', term: 'Sushi Cook', short: 'Salary $5. Makes 2 sushi. Trained from a Kitchen Trainee.', example: '2 sushi feed one garden house that wants 2 items.', related: ['sushi', 'sushi_chef', 'kitchen_trainee'], rule: R.kSushi }, 'ketchup:sushi_cook', 'ketchup:sushi'),
  emp({ id: 'sushi_chef', term: 'Sushi Chef', short: 'Salary $5, 1x. Makes 5 sushi.', example: 'Enough to win a full garden house of 5 demand.', related: ['sushi', 'sushi_cook'], rule: R.kSushi }, 'ketchup:sushi_chef', 'ketchup:sushi'),
  emp({ id: 'noodle_cook', term: 'Noodle Cook', short: 'Salary $5. Makes 6 noodles. Trained from a Kitchen Trainee.', example: 'Six noodles cover two awkward 3-item houses.', related: ['noodles', 'noodle_chef', 'kitchen_trainee'], rule: R.kNoodles }, 'ketchup:noodle_cook', 'ketchup:noodles'),
  emp({ id: 'noodle_chef', term: 'Noodle Chef', short: 'Salary $5, 1x. Makes 16 noodles.', example: 'Sixteen noodles can feed most of the town’s leftovers.', related: ['noodles', 'noodle_cook'], rule: R.kNoodles }, 'ketchup:noodle_chef', 'ketchup:noodles'),
  emp({ id: 'barista_trainee', term: 'Barista Trainee', short: 'Entry level, no salary. Makes 1 coffee. Training it into a Barista also places a coffee shop.', example: 'Train it, and a coffee shop appears within range 2 of your restaurant.', related: ['coffee', 'barista', 'coffee_shop'], rule: R.kCoffee }, 'ketchup:barista_trainee', 'ketchup:coffee'),
  emp({ id: 'barista', term: 'Barista', short: 'Salary $5. Makes 2 coffee. Training it into a Lead Barista places another coffee shop.', example: 'Two coffees sold to two passing houses.', related: ['coffee', 'barista_trainee', 'lead_barista'], rule: R.kCoffee }, 'ketchup:barista', 'ketchup:coffee'),
  emp({ id: 'lead_barista', term: 'Lead Barista', short: 'Salary $5, 1x. Makes 5 coffee.', example: 'Five coffees for a chain of shops along a busy road.', related: ['coffee', 'barista'], rule: R.kCoffee }, 'ketchup:lead_barista', 'ketchup:coffee'),
  emp({ id: 'lobbyist', term: 'Lobbyist', short: 'Entry level, salary $5. Places one road or park tile within road range 2 of your entrances.', example: 'Build a road to a house that had no route to you; it opens at Clean up.', related: ['lobbyist_road', 'park', 'roadworks', 'first_lobbyist_used'], rule: R.kLobbyists }, 'ketchup:lobbyist', 'ketchup:lobbyists'),
  emp({ id: 'mass_marketeer', term: 'Mass Marketeer', short: 'Salary $5. Places no campaign; instead every campaign on the board runs one extra time this Marketing phase.', example: 'Your billboard adds 2 demand this round instead of 1, and loses only 1 duration token.', related: ['module_mass_marketeers', 'marketing_trainee', 'marketing_phase'], rule: R.kMass }, 'ketchup:mass_marketeer', 'ketchup:massMarketeers'),
  emp({ id: 'rural_marketeer', term: 'Rural Marketeer', short: 'Salary $5. Places an eternal giant billboard beside the rural area; the marketeer is busy for the rest of the game.', example: 'A burger giant billboard: +2 burgers on the rural area every round.', related: ['giant_billboard', 'rural_area', 'first_rural_marketeer_used'], rule: R.kRural }, 'ketchup:rural_marketeer', 'ketchup:ruralMarketeers'),
  emp({ id: 'gourmet_food_critic', term: 'Gourmet Food Critic', short: 'Salary $5. Places a gourmet guide that markets to every garden house, for up to 3 Marketing phases.', example: 'Three garden houses each get a pizza every round for 3 rounds.', related: ['gourmet_guide', 'garden'], rule: R.kGourmet }, 'ketchup:gourmet_food_critic', 'ketchup:gourmetCritics'),
  emp({ id: 'night_shift_manager', term: 'Night Shift Manager', short: 'Entry level, salary $5, 1x. A manager with 0 slots that sits in a CEO slot; every salary-free card you have at work acts twice.', example: 'Your Kitchen Trainee makes 2 items and your Waitress earns $6.', related: ['module_night_shift', 'manager', 'salary'], rule: R.kNight }, 'ketchup:night_shift_manager', 'ketchup:nightShift'),
  emp({ id: 'b_movie_star', term: 'B-Movie Star', short: 'Salary $5. Trained from a Waitress; at work, you choose turn order before everyone and win every waitress tie, but get no $3 tip.', example: 'Even with 0 open slots you pick turn position first.', related: ['module_movie_stars', 'waitress', 'turn_order', 'tie_break'], rule: R.kStars }, 'ketchup:b_movie_star', 'ketchup:movieStars'),
  emp({ id: 'c_movie_star', term: 'C-Movie Star', short: 'Salary $5. Like the B-Movie Star but second: chooses turn order after a B star, wins ties except against B.', example: 'Bo has the B star and you the C: Bo picks first, you second.', related: ['b_movie_star', 'module_movie_stars'], rule: R.kStars }, 'ketchup:c_movie_star', 'ketchup:movieStars'),
  emp({ id: 'd_movie_star', term: 'D-Movie Star', short: 'Salary $5. Third movie star: chooses turn order after B and C, wins ties except against them. Only with 5–6 players.', example: 'A D star still beats every player without a star in a waitress tie.', related: ['b_movie_star', 'c_movie_star'], rule: R.kStars }, 'ketchup:d_movie_star', 'ketchup:movieStars'),
];

const KETCHUP_MILESTONES: GlossaryEntry[] = [
  ms({ id: 'first_marketeer_used', term: 'First Marketeer Used', short: 'Place a campaign with any marketeer. You earn $5 for every demand token your campaigns place, and your Dinnertime score gets −2.', example: 'Your billboard adds 2 tokens: +$10 straight away.', related: ['used_card', 'campaign'], rule: R.kMilestones }, 'ketchup:first_marketeer_used', 'ketchup:newMilestones'),
  ms({ id: 'first_marketing_trainee_used', term: 'First Marketing Trainee Used', short: 'Use a Marketing Trainee. Get a free Kitchen Trainee and Errand Boy on the beach.', example: 'Two free starter cards ready for next round.', related: ['marketing_trainee', 'used_card'], rule: R.kMilestones }, 'ketchup:first_marketing_trainee_used', 'ketchup:newMilestones'),
  ms({ id: 'first_campaign_manager_used', term: 'First Campaign Manager Used', short: 'Use a Campaign Manager. This turn it may place a second tile of the same type, good and duration.', example: 'Two pizza mailboxes in two different blocks from one card.', related: ['campaign_manager', 'mailbox'], rule: R.kMilestones }, 'ketchup:first_campaign_manager_used', 'ketchup:newMilestones'),
  ms({ id: 'first_brand_manager_used', term: 'First Brand Manager Used', short: 'Use a Brand Manager. If the airplane that earns it was placed by that Brand Manager, it may advertise 2 different goods.', example: 'One airplane marketing burger and beer each round.', related: ['brand_manager', 'airplane'], rule: R.kMilestones }, 'ketchup:first_brand_manager_used', 'ketchup:newMilestones'),
  ms({ id: 'first_brand_director_used', term: 'First Brand Director Used', short: 'Use a Brand Director. Every radio you place from now on is eternal (the director stays busy and still costs salary).', example: 'Your radio markets 9 tiles of houses for the rest of the game.', related: ['brand_director', 'radio', 'eternal_campaign'], rule: R.kMilestones }, 'ketchup:first_brand_director_used', 'ketchup:newMilestones'),
  ms({ id: 'first_burger_sold', term: 'First Burger Sold', short: 'Sell a burger. Your CEO has 4 slots for the rest of the game, whatever the reserve cards say.', example: 'One more worker every round from now on.', related: ['ceo_slots', 'burger'], rule: R.kMilestones }, 'ketchup:first_burger_sold', 'ketchup:newMilestones'),
  ms({ id: 'first_pizza_sold', term: 'First Pizza Sold', short: 'Sell a pizza. This round, for each of the first three houses that buy pizza, the seller places a 2-round pizza radio on that house’s tile.', example: 'You sell pizza to house 5: a pizza radio appears on house 5’s tile.', related: ['radio', 'pizza'], rule: R.kMilestones }, 'ketchup:first_pizza_sold', 'ketchup:newMilestones'),
  ms({ id: 'first_lemonade_sold', term: 'First Lemonade Sold', short: 'Sell a lemonade. You may train cards that are at work, if the new card has the same colour.', example: 'Train your working Junior VP into a Vice President without benching it.', related: ['training', 'lemonade'], rule: R.kMilestones }, 'ketchup:first_lemonade_sold', 'ketchup:newMilestones'),
  ms({ id: 'first_beer_sold', term: 'First Beer Sold', short: 'Sell a beer. At Payday you may pay salaries with food or drink tokens: 1 token per salary.', example: 'Pay a $5 salary with a leftover burger.', related: ['salary', 'beer'], rule: R.kMilestones }, 'ketchup:first_beer_sold', 'ketchup:newMilestones'),
  ms({ id: 'first_coke_sold', term: 'First Soda Sold', short: 'Sell a soft drink. You get a freezer: keep up to 10 items at Clean up (not coffee).', example: 'Keep 4 pizzas and 2 beers for next round.', related: ['freezer', 'soft_drink'], rule: R.kMilestones, aliases: ['first soft drink sold', 'first coke sold'] }, 'ketchup:first_coke_sold', 'ketchup:newMilestones'),
  ms({ id: 'first_recruiting_girl_used', term: 'First Recruiting Girl Used', short: 'Use a Recruiting Girl. Take an Executive VP (10 slots) to the beach, and never pay its salary.', example: 'Next round one CEO slot carries ten workers.', related: ['recruiting_girl', 'executive_vp'], rule: R.kMilestones }, 'ketchup:first_recruiting_girl_used', 'ketchup:newMilestones'),
  ms({ id: 'first_trainer_used', term: 'First Trainer Used', short: 'Use a Trainer. Get a free Trainer, and you no longer have to fire people you cannot pay (pay what you can).', example: 'Short $5 at Payday: you keep everyone.', related: ['trainer', 'payday'], rule: R.kMilestones }, 'ketchup:first_trainer_used', 'ketchup:newMilestones'),
  ms({ id: 'first_discount_manager_used', term: 'First Discount Manager Used', short: 'Use a Discount Manager. Each round you discount by $3 or more, $100 leaves the bank for good, speeding up the end.', example: 'Your discounts burn $100 of the bank every round.', related: ['discount_manager', 'bank'], rule: R.kMilestones }, 'ketchup:first_discount_manager_used', 'ketchup:newMilestones'),
  ms({ id: 'first_house_built', term: 'First House Built', short: 'Build a house with a New Business Developer. You may stack training actions on one card.', example: 'Two Trainers on one card: two steps in a turn.', related: ['new_business_developer', 'training'], rule: R.kMilestones }, 'ketchup:first_house_built', 'ketchup:newMilestones'),
  ms({ id: 'first_new_restaurant', term: 'First New Restaurant', short: 'Place a new restaurant. You also build a free eternal mailbox near it, for any good you choose.', example: 'Your new restaurant arrives with its own advert next door.', related: ['restaurant', 'mailbox', 'local_manager'], rule: R.kMilestones }, 'ketchup:first_new_restaurant', 'ketchup:newMilestones'),
  ms({ id: 'first_waitress_used', term: 'First Waitress Used', short: 'Use a Waitress. Your salaries cost $3 each instead of $5.', example: 'Five salaried cards: $15 at Payday instead of $25.', related: ['waitress', 'salary'], rule: R.kMilestones }, 'ketchup:first_waitress_used', 'ketchup:newMilestones'),
  ms({ id: 'first_cart_operator_used', term: 'First Cart Operator Used', short: 'Use a Cart Operator. Cart Operators and Zeppelins collect 4 per source, Truck Drivers 6.', example: 'Two sources on the route: 8 drinks from one Cart Operator.', related: ['cart_operator', 'truck_driver'], rule: R.kMilestones }, 'ketchup:first_cart_operator_used', 'ketchup:newMilestones'),
  ms({ id: 'first_lobbyist_used', term: 'First Lobbyist Used', short: 'Place a road or park. Immediately add one extra map tile next to the town.', example: 'You place a new tile with two houses right beside your restaurant.', related: ['lobbyist', 'map_tile'], rule: R.kLobbyists }, 'ketchup:first_lobbyist_used', 'ketchup:lobbyists'),
  ms({ id: 'first_coffee_sold', term: 'First Coffee Sold', short: 'Sell coffee. At Clean up you place one extra coffee shop anywhere.', example: 'Drop a coffee shop on the busiest road in town.', related: ['coffee', 'coffee_shop'], rule: R.kCoffee }, 'ketchup:first_coffee_sold', 'ketchup:coffee'),
  ms({ id: 'first_rural_marketeer_used', term: 'First Rural Marketeer Used', short: 'Use a Rural Marketeer. You may place a freeway linking the map edge to the rural area.', example: 'Put the freeway next to your restaurant so you reach the rural area first.', related: ['freeway', 'rural_area', 'rural_marketeer'], rule: R.kRural }, 'ketchup:first_rural_marketeer_used', 'ketchup:ruralMarketeers'),
  ms({ id: 'ketchup_milestone', term: 'Ketchup ("Someone sells your demand")', short: 'Earned at the end of a Dinnertime in which another player sold to demand your marketeer created. Your Dinnertime score is −1 from then on.', example: 'Bo sold to a house your billboard filled. From the next Dinnertime your $10 + 2 counts as 11, beating Bo’s $10 + 2 = 12.', related: ['module_ketchup', 'winning_a_sale', 'demand'], rule: R.kKetchup }, 'ketchup:ketchup', 'ketchup:ketchup'),
];

export const GLOSSARY: readonly GlossaryEntry[] = [
  ...BASICS,
  ...COMPANY,
  ...BOARD,
  ...DINNER,
  ...MARKETING,
  ...MONEY,
  ...FOOD,
  ...EMPLOYEES,
  ...MILESTONES,
  ...KETCHUP_CONCEPTS,
  ...MODULES,
  ...KETCHUP_EMPLOYEES,
  ...KETCHUP_MILESTONES,
];
