/**
 * The 18 base milestones (docs/rules/milestones.md, DLX p11, p34–35). Data only: triggers are
 * evaluated and effects applied by rules/milestones.ts and the phase code that reads
 * `PlayerState.milestones`. No copy counts (milestones.md general rule 5).
 */
import type { MilestoneDef } from '../types/content.js';

const m = (def: Omit<MilestoneDef, 'module'>): MilestoneDef => ({ module: 'base', ...def });

export const BASE_MILESTONES: readonly MilestoneDef[] = [
  m({
    id: 'first_billboard',
    name: 'First Billboard Campaign',
    trigger: { kind: 'campaignPlaced', campaignKind: 'billboard' },
    effects: [{ kind: 'noMarketeerSalary' }, { kind: 'eternalCampaigns' }],
    timing: 'immediately',
    text: 'No salary for campaign managers, brand managers and brand directors. All campaigns you launch from now on (this one included) are eternal.',
    rulesRef: 'milestones.md; base.md §6.4, §8.3; DLX p20, p35',
  }),
  m({
    id: 'first_train',
    name: 'First to Train an Employee',
    trigger: { kind: 'trained' },
    effects: [{ kind: 'salaryDiscount', amount: 15 }],
    timing: 'thisPayday',
    text: 'Pay $15 less salary each Payday (minimum $0).',
    rulesRef: 'milestones.md; base.md §8.3; DLX p34',
  }),
  m({
    id: 'first_hire_3',
    name: 'First to Hire 3 Employees in 1 Turn',
    trigger: { kind: 'hiredThisTurn', count: 3 },
    effects: [{ kind: 'gainEmployees', employees: [{ id: 'management_trainee', count: 2 }], trainableThisTurn: true }],
    timing: 'immediately',
    text: 'Immediately gain 2 Management Trainees (fewer if the supply is short).',
    rulesRef: 'milestones.md; base.md §6.2, §6.3; DLX p34',
  }),
  m({
    id: 'first_burger_marketed',
    name: 'First Burger Marketed',
    trigger: { kind: 'campaignPlaced', good: 'burger' },
    effects: [{ kind: 'saleBonus', good: 'burger', amount: 5 }],
    timing: 'immediately',
    text: '+$5 per burger sold (not doubled by gardens).',
    rulesRef: 'milestones.md; base.md §7; DLX p35',
  }),
  m({
    id: 'first_pizza_marketed',
    name: 'First Pizza Marketed',
    trigger: { kind: 'campaignPlaced', good: 'pizza' },
    effects: [{ kind: 'saleBonus', good: 'pizza', amount: 5 }],
    timing: 'immediately',
    text: '+$5 per pizza sold (not doubled by gardens).',
    rulesRef: 'milestones.md; base.md §7; DLX p35',
  }),
  m({
    id: 'first_drink_marketed',
    name: 'First Drink Marketed',
    trigger: { kind: 'campaignPlaced', good: 'anyDrink' },
    effects: [{ kind: 'saleBonus', good: 'anyDrink', amount: 5 }],
    timing: 'immediately',
    text: '+$5 per drink sold, all drink types (not doubled by gardens).',
    rulesRef: 'milestones.md; base.md §7; DLX p35',
  }),
  m({
    id: 'first_errand_boy',
    name: 'First Errand Boy Played',
    trigger: { kind: 'atWork', employees: ['errand_boy'] },
    effects: [{ kind: 'buyerPerSourceBonus', amount: 1 }],
    timing: 'immediately',
    text: 'Errand boys get 2 drinks; other buyers +1 per source.',
    rulesRef: 'milestones.md; base.md §6.5; DLX p34',
  }),
  m({
    id: 'first_20',
    name: 'First to Have $20',
    trigger: { kind: 'cash', amount: 20, when: 'anytime' },
    effects: [{ kind: 'peekReserves' }],
    timing: 'immediately',
    text: 'You may look at the face-down reserve cards.',
    rulesRef: 'milestones.md; base.md §7; DLX p28, p34; questions.md Q-B1',
  }),
  m({
    id: 'first_burger_produced',
    name: 'First Burger Produced',
    trigger: { kind: 'produced', food: 'burger' },
    effects: [{ kind: 'gainEmployees', employees: [{ id: 'burger_cook', count: 1 }], trainableThisTurn: false }],
    timing: 'immediately',
    text: 'Gain a Burger Cook on the beach.',
    rulesRef: 'milestones.md; base.md §6.5; DLX p34',
  }),
  m({
    id: 'first_pizza_produced',
    name: 'First Pizza Produced',
    trigger: { kind: 'produced', food: 'pizza' },
    effects: [{ kind: 'gainEmployees', employees: [{ id: 'pizza_cook', count: 1 }], trainableThisTurn: false }],
    timing: 'immediately',
    text: 'Gain a Pizza Cook on the beach.',
    rulesRef: 'milestones.md; base.md §6.5; DLX p34',
  }),
  m({
    id: 'first_waitress',
    name: 'First Waitress Played',
    trigger: { kind: 'atWork', employees: ['waitress'] },
    effects: [{ kind: 'waitressTip', amount: 2 }],
    timing: 'immediately',
    text: '+$2 per waitress at the end of Dinnertime ($5 each).',
    rulesRef: 'milestones.md; base.md §7; DLX p34',
  }),
  m({
    id: 'first_throw_away',
    name: 'First to Throw Away Food or Drink',
    trigger: { kind: 'discarded' },
    effects: [{ kind: 'freezer', capacity: 10 }],
    timing: 'nextCleanup',
    text: 'Gain a freezer: from the next Cleanup, keep up to 10 unsold items.',
    rulesRef: 'milestones.md; base.md §10; DLX p33, p35',
  }),
  m({
    id: 'first_lower_prices',
    name: 'First to Lower Prices',
    trigger: { kind: 'startOfDinnertime', condition: 'lowerPrices' },
    effects: [{ kind: 'unitPrice', delta: -1 }],
    timing: 'immediately',
    text: 'Item price permanently −$1.',
    rulesRef: 'milestones.md; base.md §7; DLX p28, p35',
  }),
  m({
    id: 'first_cart_operator',
    name: 'First Cart Operator Played',
    trigger: { kind: 'atWork', employees: ['cart_operator'] },
    effects: [{ kind: 'buyerRangeBonus', amount: 1 }],
    timing: 'immediately',
    text: 'Cart operators, truck drivers and zeppelin pilots +1 range.',
    rulesRef: 'milestones.md; base.md §6.5; DLX p34',
  }),
  m({
    id: 'first_airplane',
    name: 'First Airplane Campaign',
    trigger: { kind: 'campaignPlaced', campaignKind: 'airplane' },
    effects: [{ kind: 'orderSlots', amount: 2 }],
    timing: 'nextOrderOfBusiness',
    text: '+2 open slots when choosing turn order.',
    rulesRef: 'milestones.md; base.md §5; DLX p35',
  }),
  m({
    id: 'first_radio',
    name: 'First Radio Campaign',
    trigger: { kind: 'campaignPlaced', campaignKind: 'radio' },
    effects: [{ kind: 'radioTokens', amount: 2 }],
    timing: 'thisMarketing',
    text: 'Your radios place 2 demand per house reached (as many as fit).',
    rulesRef: 'milestones.md; base.md §9; DLX p35',
  }),
  m({
    id: 'first_100',
    name: 'First to Have $100',
    trigger: { kind: 'cash', amount: 100, when: 'anytime' },
    effects: [{ kind: 'ceoIsCfo' }],
    timing: 'nextDinnertime',
    text: 'Your CEO acts as a CFO from the next Dinnertime. Fire your CFO; you may never train one again.',
    rulesRef: 'milestones.md; base.md §7; DLX p34; questions.md Q-B6',
  }),
  m({
    id: 'first_pay_20',
    name: 'First to Pay $20 or More in Salaries',
    trigger: { kind: 'salaryPaid', amount: 20 },
    effects: [{ kind: 'stackTraining' }],
    timing: 'nextTurn',
    text: 'You may stack several training actions on one employee.',
    rulesRef: 'milestones.md; base.md §6.3, §8.5; DLX p29, p34',
  }),
];
