/**
 * Canned states for tests, UI and 3D development. Each is built by the state builder; the JSON
 * copies next to this file are generated by `npm run fixtures` and checked by a test.
 */
import type { GameState } from '../../types/state.js';
import { stateBuilder } from '../stateBuilder.js';

/** 3x4 tiles, 3 players. ASCII: see testing/board.ts renderAscii. */
const THREE_PLAYER_MAP = [
  ['A', 'O1', 'L', 'E'],
  ['K', 'C', 'N2', 'F'],
  ['T', 'D3', 'G', 'B1'],
];

/** Ketchup New Districts + Lobbyists map (tiles X, U, W, Y, Z, V). */
const KETCHUP_MAP = [
  ['X', 'U', 'W', 'C'],
  ['Y', 'Z', 'V', 'A'],
  ['O', 'E', 'K', 'T'],
];

/** base.md §2.6: first restaurant placement, round 1 (reverse order); p3 placed, p2 to act. */
export function setupFixture(): GameState {
  return stateBuilder({ players: 3, seed: 101 })
    .tiles(THREE_PLAYER_MAP)
    .round(0)
    .restaurant('p3', 8, 3, 'NW')
    .phase({ kind: 'setup.restaurants', round: 1, order: ['p3', 'p2', 'p1'], idx: 1, placed: ['p3'], passed: [] })
    .build();
}

/** base.md §4: round 2 Restructuring. Cards hired in round 1 are in hand; p1 has submitted. */
export function restructuringFixture(): GameState {
  const b = stateBuilder({ players: 3, seed: 102 })
    .tiles(THREE_PLAYER_MAP)
    .round(2)
    .restaurant('p1', 3, 3, 'NW')
    .restaurant('p2', 8, 3, 'NW')
    .restaurant('p3', 15, 10, 'NE')
    .card('p1', 'marketing_trainee', 'hand', 'p1-mkt')
    .card('p1', 'waitress', 'hand', 'p1-w')
    .card('p1', 'management_trainee', 'hand', 'p1-mt')
    .card('p2', 'recruiting_girl', 'hand', 'p2-rg')
    .card('p2', 'kitchen_trainee', 'hand', 'p2-kt')
    .card('p3', 'errand_boy', 'hand', 'p3-eb')
    .card('p3', 'trainer', 'hand', 'p3-tr')
    .reserve('p1', { kind: 'standard', amount: 300, ceoSlots: 4 })
    .reserve('p2', { kind: 'standard', amount: 100, ceoSlots: 2 })
    .reserve('p3', { kind: 'standard', amount: 200, ceoSlots: 3 })
    .phase({ kind: 'restructuring' });
  return b
    .secret('p1', { structureDraft: { ceo: b.ceoUid('p1'), ceoSubs: ['p1-mt', 'p1-w'], managerSubs: { 'p1-mt': ['p1-mkt'] } } })
    .build();
}

/** base.md §6: round 3 Working, p2 active in the marketing sub-step; p1 done; an eternal billboard on the map. */
export function workingFixture(): GameState {
  const b = stateBuilder({ players: 3, seed: 103 })
    .tiles(THREE_PLAYER_MAP)
    .round(3)
    .cash('p1', 30)
    .cash('p2', 15)
    .cash('p3', 5)
    .restaurant('p1', 3, 3, 'NW')
    .restaurant('p2', 8, 3, 'NW')
    .restaurant('p3', 15, 10, 'NE')
    // p1: eternal billboard from round 2 (first_billboard), waitress + pricing manager at work.
    .marketeerCampaign('marketing_trainee', 'p1-mkt', {
      owner: 'p1',
      kind: 'billboard',
      number: 11,
      goods: ['burger'],
      placement: { kind: 'board', x: 11, y: 5, w: 3, h: 2 },
      remaining: 1,
      eternal: true,
      id: 'cmp-p1-bb11',
    })
    .card('p1', 'waitress', 'work', 'p1-w')
    .card('p1', 'pricing_manager', 'work', 'p1-pm')
    .card('p1', 'kitchen_trainee', 'beach', 'p1-kt')
    .milestone('p1', 'first_billboard', 2)
    .milestone('p1', 'first_burger_marketed', 2)
    .milestone('p1', 'first_lower_prices', 3)
    // p2 (active): management trainee holding kitchen + marketing trainees; recruiter; errand boy.
    .card('p2', 'management_trainee', 'work', 'p2-mt')
    .card('p2', 'recruiting_girl', 'work', 'p2-rg')
    .card('p2', 'errand_boy', 'work', 'p2-eb')
    .card('p2', 'cart_operator', 'work', 'p2-co')
    .card('p2', 'kitchen_trainee', { under: 'p2-mt' }, 'p2-kt')
    .card('p2', 'marketing_trainee', { under: 'p2-mt' }, 'p2-mkt')
    .card('p2', 'waitress', 'beach', 'p2-w')
    .card('p2', 'trainer', 'beach', 'p2-tr')
    .milestone('p2', 'first_errand_boy', 3)
    .milestone('p2', 'first_hire_3', 2)
    .card('p3', 'errand_boy', 'work', 'p3-eb')
    .card('p3', 'trainer', 'work', 'p3-tr')
    .inventory('p1', { burger: 1 })
    .bank({ cash: 120 })
    .phase({ kind: 'working', player: 'p2', idx: 1 });
  const ceo = b.ceoUid('p2');
  return b
    .turn({
      player: 'p2',
      stage: 'marketing',
      uses: { [ceo]: 0, 'p2-rg': 0, 'p2-mkt': 1, 'p2-kt': 1, 'p2-eb': 1, 'p2-co': 1 },
      hired: ['p2-w', 'p2-tr'],
      used: [ceo, 'p2-rg'],
    })
    .build();
}

/**
 * base.md §7: round 4 Dinnertime, first house. Houses with demand (one with a garden tile, one
 * placed house), open + coming-soon restaurants, one campaign of each base kind, drink sources.
 */
export function dinnertimeFixture(): GameState {
  const b = stateBuilder({ players: 3, seed: 104 })
    .tiles(THREE_PLAYER_MAP)
    .round(4)
    .cash('p1', 62)
    .cash('p2', 41)
    .cash('p3', 18)
    .bank({ cash: 95 })
    .restaurant('p1', 3, 3, 'NW')
    .restaurant('p1', 0, 8, 'NW', 'comingSoon')
    .restaurant('p2', 8, 3, 'NW')
    .restaurant('p3', 15, 10, 'NE')
    .garden(5, 'S')
    .placedHouse(1, 10, 3, 'E')
    .marketeerCampaign('marketing_trainee', 'p1-mkt', {
      owner: 'p1',
      kind: 'billboard',
      number: 11,
      goods: ['burger'],
      placement: { kind: 'board', x: 11, y: 5, w: 3, h: 2 },
      remaining: 1,
      eternal: true,
      id: 'cmp-p1-bb11',
    })
    .marketeerCampaign('campaign_manager', 'p2-cm', {
      owner: 'p2',
      kind: 'mailbox',
      number: 9,
      goods: ['pizza'],
      placement: { kind: 'board', x: 4, y: 8, w: 1, h: 1 },
      remaining: 2,
      id: 'cmp-p2-mb9',
    })
    .marketeerCampaign('brand_manager', 'p3-bm', {
      owner: 'p3',
      kind: 'airplane',
      number: 5,
      goods: ['beer'],
      placement: { kind: 'airplane', side: 'S', offset: 5, width: 3 },
      remaining: 3,
      id: 'cmp-p3-ap5',
    })
    .marketeerCampaign('brand_director', 'p2-bd', {
      owner: 'p2',
      kind: 'radio',
      number: 1,
      goods: ['lemonade'],
      placement: { kind: 'board', x: 14, y: 8, w: 1, h: 1 },
      remaining: 1,
      id: 'cmp-p2-rd1',
    })
    .demand(1, ['burger', 'burger'], 'p1', 'cmp-p1-bb11')
    .demand(2, ['burger'], 'p1', 'cmp-p1-bb11')
    .demand(5, ['beer', 'beer', 'lemonade'], 'p3', 'cmp-p3-ap5')
    .demand(18, ['pizza'], 'p2', 'cmp-p2-mb9')
    .demand(12, ['lemonade', 'lemonade'], 'p2', 'cmp-p2-rd1')
    .card('p1', 'waitress', 'work', 'p1-w')
    .card('p1', 'pricing_manager', 'work', 'p1-pm')
    .card('p1', 'kitchen_trainee', 'work', 'p1-kt')
    .card('p1', 'local_manager', 'beach', 'p1-lm')
    .card('p2', 'waitress', 'work', 'p2-w')
    .card('p2', 'kitchen_trainee', 'work', 'p2-kt')
    .card('p2', 'cart_operator', 'work', 'p2-co')
    .card('p3', 'errand_boy', 'work', 'p3-eb')
    .card('p3', 'burger_cook', 'work', 'p3-bc')
    .inventory('p1', { burger: 4, beer: 2 })
    .inventory('p2', { pizza: 3, lemonade: 3 })
    .inventory('p3', { burger: 3, beer: 1, soft_drink: 1 })
    .milestone('p1', 'first_billboard', 2)
    .milestone('p1', 'first_burger_marketed', 2)
    .milestone('p1', 'first_lower_prices', 3)
    .milestone('p2', 'first_pizza_marketed', 3)
    .milestone('p3', 'first_airplane', 3)
    .milestone('p3', 'first_burger_produced', 4);
  return b.phase({ kind: 'dinnertime', houses: b.houseOrder(), idx: 0 }).build();
}

/**
 * Ketchup board entities for 3D/UI work: apartments, printed garden (tile W), parks (tile Z and a
 * placed one), coffee shops, an under-construction lobbyist road with roadworks, a freeway, the
 * rural area with a giant billboard, a gourmet guide, and Ketchup goods in stock.
 */
export function ketchupFixture(): GameState {
  const b = stateBuilder({ players: 3, seed: 105 })
    .modules([
      'ketchup:newDistricts',
      'ketchup:lobbyists',
      'ketchup:coffee',
      'ketchup:kimchi',
      'ketchup:sushi',
      'ketchup:ruralMarketeers',
      'ketchup:gourmetCritics',
    ])
    .tiles(KETCHUP_MAP)
    .round(5)
    .cash('p1', 80)
    .cash('p2', 55)
    .cash('p3', 32)
    .restaurant('p1', 12, 0, 'SE')
    .restaurant('p2', 18, 10, 'NW')
    .restaurant('p3', 10, 13, 'NW')
    .entity({ kind: 'coffeeShop', id: 'ent-cs-p1', owner: 'p1', x: 16, y: 3 })
    .entity({ kind: 'coffeeShop', id: 'ent-cs-p3', owner: 'p3', x: 0, y: 13 })
    .entity({
      kind: 'park',
      id: 'ent-park-1',
      x: 3,
      y: 13,
      w: 3,
      h: 2,
      printed: false,
      // An L park tile (questions.md Q-K1), mirrored side up.
      cells: [
        { x: 3, y: 13 },
        { x: 4, y: 13 },
        { x: 5, y: 13 },
        { x: 3, y: 14 },
      ],
    })
    .entity({
      kind: 'lobbyistRoad',
      id: 'ent-road-1',
      owner: 'p2',
      cells: [
        { x: 3, y: 10 },
        { x: 4, y: 10 },
      ],
      underConstruction: true,
      arrows: [
        { from: { x: 3, y: 10 }, dir: 'W' },
        { from: { x: 4, y: 10 }, dir: 'E' },
      ],
    })
    .entity({ kind: 'roadworks', id: 'ent-rw-1', x: 2, y: 10, road: 'ent-road-1' })
    .entity({ kind: 'roadworks', id: 'ent-rw-2', x: 5, y: 10, road: 'ent-road-1' })
    .ruralArea();
  b.entity({ kind: 'freeway', id: 'ent-fw-1', owner: 'p3', side: 'E', offset: 7, tile: b.tileId(1, 3) });
  b.marketeerCampaign('ketchup:rural_marketeer', 'p3-rm', {
    owner: 'p3',
    kind: 'giantBillboard',
    number: 21,
    goods: ['burger'],
    placement: { kind: 'rural', side: 'N' },
    remaining: 1,
    eternal: true,
    id: 'cmp-p3-gb',
  })
    .marketeerCampaign('ketchup:gourmet_food_critic', 'p1-gc', {
      owner: 'p1',
      kind: 'gourmetGuide',
      number: 17,
      goods: ['pizza'],
      placement: { kind: 'offBoard' },
      remaining: 2,
      id: 'cmp-p1-gg17',
    })
    .demand(1000, ['burger', 'burger', 'burger', 'burger'], 'p3', 'cmp-p3-gb')
    .demand(3.14, ['soft_drink', 'soft_drink'], 'p2', null)
    .demand(25, ['pizza', 'lemonade'], 'p1', 'cmp-p1-gg17')
    .card('p1', 'ketchup:lead_barista', 'work', 'p1-lb')
    .card('p1', 'waitress', 'work', 'p1-w')
    .card('p2', 'ketchup:lobbyist', 'work', 'p2-lob')
    .card('p2', 'ketchup:kimchi_master', 'work', 'p2-km')
    .card('p3', 'ketchup:sushi_cook', 'work', 'p3-sc')
    .card('p3', 'burger_cook', 'work', 'p3-bc')
    .inventory('p1', { coffee: 5, pizza: 2, lemonade: 1 })
    .inventory('p2', { kimchi: 1, soft_drink: 4 })
    .inventory('p3', { burger: 6, sushi: 2 });
  return b.phase({ kind: 'dinnertime', houses: b.houseOrder(), idx: 0 }).build();
}

export const FIXTURES = {
  setup: setupFixture,
  restructuring: restructuringFixture,
  working: workingFixture,
  dinnertime: dinnertimeFixture,
  ketchup: ketchupFixture,
} as const satisfies Record<string, () => GameState>;

export type FixtureName = keyof typeof FIXTURES;
